export const STOCK_DATA = {
  categories: [
    {
      id: "banking-financial",
      name: "Banking & Financial Services",
      count: 101,
      icon: "Landmark",
      description: "Banks, NBFCs, Housing Finance, Insurance, Asset Management, Microfinance & Financial Infrastructure",
      driver: "Credit growth, net interest margins (NIM), asset quality, liquidity & economic activity.",
      risk: "Non-performing assets (NPAs), credit defaults, interest rate volatility & regulatory shifts."
    },
    {
      id: "capital-goods",
      name: "Capital Goods & Industrial Manufacturing",
      count: 63,
      icon: "Factory",
      description: "Defense electronics, heavy engineering, railway equipment, power transmission, cables, construction EPC & automation.",
      driver: "Government capex, private industrial expansion, infrastructure spending & order book execution.",
      risk: "Economic slowdown, raw material price escalation, project delays & supply chain bottlenecks."
    },
    {
      id: "healthcare-pharma",
      name: "Healthcare & Pharmaceuticals",
      count: 48,
      icon: "Activity",
      description: "Formulations, APIs, biosimilars, diagnostics, hospital chains & contract research.",
      driver: "Global generic export demand, chronic care prevalence, healthcare infrastructure expanding.",
      risk: "USFDA audit warnings/observations, price controls, generic price erosion & drug trial failures."
    },
    {
      id: "automobiles",
      name: "Automobiles & Auto Components",
      count: 38,
      icon: "Car",
      description: "Passenger cars, commercial vehicles, 2-wheelers, EV mobility, batteries, tyres & precision auto parts.",
      driver: "Vehicle replacement cycles, EV adoption rate, rural income levels & export demand.",
      risk: "Cyclical consumer demand, commodity input costs, EV disruption timing & high interest rates."
    },
    {
      id: "it-technology",
      name: "IT & Technology",
      count: 27,
      icon: "Cpu",
      description: "IT services, enterprise software, ER&D engineering, cloud communications & ad-tech.",
      driver: "US & European enterprise tech budgets, digital transformation, cloud/AI migration.",
      risk: "US/EU macroeconomic slowdown, tech spending cuts, currency fluctuations & margin pressure."
    },
    {
      id: "fmcg",
      name: "FMCG & Everyday Consumer Products",
      count: 28,
      icon: "ShoppingBag",
      description: "Food & beverages, home care, personal hygiene, dairy, packaged foods & tobacco.",
      driver: "Rural consumption growth, premiumisation, population growth & brand distribution strength.",
      risk: "High valuations, raw material inflation, unorganised competition & sluggish volume growth."
    },
    {
      id: "chemicals",
      name: "Chemicals & Specialty Materials",
      count: 26,
      icon: "FlaskConical",
      description: "Agrochemicals, specialty fluorochemicals, amines, polymers & fertilizers.",
      driver: "China+1 global supply chain shift, agricultural yield demand & R&D customization.",
      risk: "Global oversupply from China, commodity price dumps, environmental regulations & export slowdown."
    },
    {
      id: "metals-mining",
      name: "Metals & Mining",
      count: 18,
      icon: "Pickaxe",
      description: "Steel, aluminium, zinc, copper, iron ore & coal mining.",
      driver: "Global commodity prices, China industrial demand, domestic infrastructure capex.",
      risk: "Commodity price crashes, global trade tariffs, high capital intensity & debt levels."
    },
    {
      id: "oil-gas-energy",
      name: "Oil, Gas & Energy",
      count: 34,
      icon: "Zap",
      description: "Oil refining & exploration, gas pipelines, city gas distribution, power generation & solar/wind equipment.",
      driver: "Industrial electricity demand, crude oil refining margins, green energy transition.",
      risk: "Geopolitical shocks, volatile crude prices, heavy government regulation & environmental transition risks."
    },
    {
      id: "consumer-durables",
      name: "Consumer Durables & Electronics",
      count: 16,
      icon: "Tv",
      description: "Air conditioners, home appliances, electronics manufacturing (EMS), jewellery & retail.",
      driver: "Rising middle-class disposable income, summer heatwaves (for ACs), PLI scheme incentives.",
      risk: "Intense price competition, input component costs & seasonal demand variations."
    },
    {
      id: "construction-infra",
      name: "Construction & Infrastructure",
      count: 24,
      icon: "Building2",
      description: "Roads, highways, urban metro systems, railway EPC & power project execution.",
      driver: "National Infrastructure Pipeline spending, highway awards & urban transit expansion.",
      risk: "Land acquisition delays, working capital lockup, high leverage & weather disruptions."
    },
    {
      id: "cement-materials",
      name: "Cement & Building Materials",
      count: 11,
      icon: "Layers",
      description: "Grey & white cement, ceramic tiles & plastic piping solutions.",
      driver: "Housing boom, infrastructure projects, real estate construction activity.",
      risk: "Power & fuel cost spikes (petcoke/coal), regional price wars & overcapacity."
    },
    {
      id: "realty",
      name: "Realty & Real Estate",
      count: 11,
      icon: "Building",
      description: "Residential housing developers, commercial offices, IT parks & shopping malls.",
      driver: "Urbanization, housing affordability, home loan interest rates & office leasing.",
      risk: "High home loan interest rates, inventory overhang, regulatory approvals delay."
    },
    {
      id: "telecom",
      name: "Telecom & Digital Infrastructure",
      count: 10,
      icon: "Radio",
      description: "Mobile operators, fiber optics, telecom towers & cloud messaging.",
      driver: "Data consumption surge, 5G monetization, ARPU (Average Revenue Per User) hikes.",
      risk: "Heavy capital expenditure for spectrum & network upgrades, debt burdens."
    },
    {
      id: "consumer-services",
      name: "Consumer Services, Retail & Logistics",
      count: 43,
      icon: "Truck",
      description: "Quick commerce, food delivery, hotel chains, airline travel, logistics, e-commerce & staffing.",
      driver: "Domestic leisure travel, e-commerce penetration, urban lifestyle adoption.",
      risk: "High operational cash burn, fuel price hikes, intense retail competition."
    },
    {
      id: "textiles-apparel",
      name: "Textiles & Apparel",
      count: 5,
      icon: "Shirt",
      description: "Garment manufacturing, cotton yarn, home textiles & innerwear.",
      driver: "US/EU export orders, raw cotton price stability, retail apparel growth.",
      risk: "Cotton price volatility, export order slowdowns & international trade policies."
    },
    {
      id: "media-entertainment",
      name: "Media & Entertainment",
      count: 5,
      icon: "Film",
      description: "Television broadcasting, cinema multiplexes, music streaming & digital media.",
      driver: "Ad spending recovery, box office hits & OTT subscription growth.",
      risk: "Shift to digital consumption, declining print/linear TV ads & high content creation costs."
    }
  ],

  investmentBuckets: [
    {
      id: "compounders",
      name: "High-Quality Compounders",
      color: "emerald",
      badge: "🟢 High Quality",
      criteria: "High ROE, low debt, consistent profit growth across market cycles.",
      examples: ["HDFC Bank", "TCS", "Asian Paints", "Titan Company", "Nestlé India", "Page Industries"]
    },
    {
      id: "growth",
      name: "Growth Businesses",
      color: "blue",
      badge: "🔵 High Growth",
      criteria: "Fast sales & profit expansion riding mega structural trends.",
      examples: ["Trent", "Dixon Technologies", "Kaynes Technology", "Apollo Hospitals", "Bharat Electronics"]
    },
    {
      id: "cyclical",
      name: "Cyclical Businesses",
      color: "amber",
      badge: "🟡 Cyclical",
      criteria: "Earnings fluctuate with commodity, capex or global trade cycles. Cheap in downturns.",
      examples: ["Tata Steel", "JSW Steel", "Hindalco Industries", "Larsen & Toubro", "DLF"]
    },
    {
      id: "turnaround",
      name: "Turnaround & Value",
      color: "orange",
      badge: "🟠 Value / Turnaround",
      criteria: "Low valuation multiples with improving underlying balance sheets & fundamentals.",
      examples: ["SBI", "Bank of Baroda", "NTPC", "Power Grid", "Coal India", "Tata Motors"]
    },
    {
      id: "high-risk",
      name: "High-Risk / High-Growth",
      color: "rose",
      badge: "🔴 High Risk / High Growth",
      criteria: "Very rapid revenue expansion but high valuation, regulatory risk or cash burn.",
      examples: ["Zomato/Eternal", "Ola Electric Mobility", "Suzlon Energy", "Nazara Technologies", "Go Digit"]
    }
  ],

  nifty500Weights: [
    { name: "Financial Services", weight: 20.27, color: "#3b82f6" },
    { name: "Capital Goods", weight: 12.63, color: "#8b5cf6" },
    { name: "Healthcare", weight: 10.02, color: "#10b981" },
    { name: "Auto & Auto Components", weight: 7.66, color: "#f59e0b" },
    { name: "Consumer Services", weight: 5.77, color: "#ec4899" },
    { name: "FMCG", weight: 5.68, color: "#84cc16" },
    { name: "IT & Technology", weight: 5.18, color: "#06b6d4" },
    { name: "Chemicals", weight: 5.15, color: "#6366f1" },
    { name: "Metals & Mining", weight: 3.57, color: "#64748b" },
    { name: "Power & Renewables", weight: 3.41, color: "#eab308" },
    { name: "Oil & Gas", weight: 3.39, color: "#ef4444" },
    { name: "Others (Realty, Telecom, etc)", weight: 11.27, color: "#94a3b8" }
  ],

  companies: [
    // 1. Banking & Financial Services
    { name: "360 ONE WAM", category: "banking-financial", detail: "Wealth and asset management", bucket: "growth", tier: "Strong", pe: 28.4, roe: 24.2, debt: "Low", growth5Y: "18.5%" },
    { name: "5paisa Capital", category: "banking-financial", detail: "Online stock broking", bucket: "high-risk", tier: "Average", pe: 22.1, roe: 13.5, debt: "Low", growth5Y: "14.2%" },
    { name: "AU Small Finance Bank", category: "banking-financial", detail: "Retail and small-business banking", bucket: "growth", tier: "Strong", pe: 26.5, roe: 15.1, debt: "N/A (Bank)", growth5Y: "22.4%" },
    { name: "Axis Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "turnaround", tier: "Strong", pe: 11.8, roe: 17.8, debt: "N/A (Bank)", growth5Y: "19.2%" },
    { name: "Bajaj Finance", category: "banking-financial", detail: "Consumer and business lending", bucket: "compounders", tier: "Strong", pe: 29.8, roe: 21.4, debt: "Moderate", growth5Y: "25.6%" },
    { name: "Bajaj Finserv", category: "banking-financial", detail: "Financial-services holding company", bucket: "compounders", tier: "Strong", pe: 31.2, roe: 16.2, debt: "Low", growth5Y: "18.9%" },
    { name: "Bandhan Bank", category: "banking-financial", detail: "Banking, especially retail/microfinance", bucket: "turnaround", tier: "Risky", pe: 12.4, roe: 12.1, debt: "N/A (Bank)", growth5Y: "10.5%" },
    { name: "Bank of Baroda", category: "banking-financial", detail: "Public-sector banking", bucket: "turnaround", tier: "Good", pe: 6.8, roe: 17.5, debt: "N/A (Bank)", growth5Y: "16.8%" },
    { name: "Bank of India", category: "banking-financial", detail: "Public-sector banking", bucket: "turnaround", tier: "Average", pe: 7.2, roe: 12.8, debt: "N/A (Bank)", growth5Y: "11.2%" },
    { name: "Bank of Maharashtra", category: "banking-financial", detail: "Public-sector banking", bucket: "turnaround", tier: "Good", pe: 8.1, roe: 18.9, debt: "N/A (Bank)", growth5Y: "21.5%" },
    { name: "Canara Bank", category: "banking-financial", detail: "Public-sector banking", bucket: "turnaround", tier: "Good", pe: 6.5, roe: 18.2, debt: "N/A (Bank)", growth5Y: "17.4%" },
    { name: "Central Bank of India", category: "banking-financial", detail: "Public-sector banking", bucket: "turnaround", tier: "Average", pe: 11.5, roe: 10.5, debt: "N/A (Bank)", growth5Y: "9.8%" },
    { name: "Cholamandalam Investment", category: "banking-financial", detail: "Vehicle and business finance", bucket: "growth", tier: "Strong", pe: 32.1, roe: 20.1, debt: "Moderate", growth5Y: "22.8%" },
    { name: "City Union Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "turnaround", tier: "Average", pe: 11.8, roe: 12.5, debt: "N/A (Bank)", growth5Y: "8.4%" },
    { name: "CSB Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "growth", tier: "Good", pe: 10.2, roe: 16.1, debt: "N/A (Bank)", growth5Y: "15.3%" },
    { name: "DCB Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "turnaround", tier: "Average", pe: 8.9, roe: 11.2, debt: "N/A (Bank)", growth5Y: "9.1%" },
    { name: "Equitas Small Finance Bank", category: "banking-financial", detail: "Retail and small-business banking", bucket: "growth", tier: "Good", pe: 14.5, roe: 14.8, debt: "N/A (Bank)", growth5Y: "18.2%" },
    { name: "Federal Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "compounders", tier: "Strong", pe: 10.6, roe: 15.6, debt: "N/A (Bank)", growth5Y: "16.5%" },
    { name: "HDFC Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "compounders", tier: "Strong", pe: 18.5, roe: 16.8, debt: "N/A (Bank)", growth5Y: "18.1%" },
    { name: "HDFC Asset Management", category: "banking-financial", detail: "Mutual-fund/asset management", bucket: "compounders", tier: "Strong", pe: 38.4, roe: 30.1, debt: "Zero", growth5Y: "17.6%" },
    { name: "HDFC Life", category: "banking-financial", detail: "Life insurance", bucket: "compounders", tier: "Good", pe: 82.5, roe: 12.5, debt: "Zero", growth5Y: "14.2%" },
    { name: "ICICI Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "compounders", tier: "Strong", pe: 17.2, roe: 18.9, debt: "N/A (Bank)", growth5Y: "21.3%" },
    { name: "ICICI Lombard", category: "banking-financial", detail: "General insurance", bucket: "compounders", tier: "Good", pe: 35.6, roe: 17.4, debt: "Zero", growth5Y: "13.8%" },
    { name: "ICICI Prudential Life", category: "banking-financial", detail: "Life insurance", bucket: "compounders", tier: "Good", pe: 74.2, roe: 10.8, debt: "Zero", growth5Y: "11.5%" },
    { name: "IDBI Bank", category: "banking-financial", detail: "Banking", bucket: "turnaround", tier: "Average", pe: 14.2, roe: 11.9, debt: "N/A (Bank)", growth5Y: "12.0%" },
    { name: "IDFC First Bank", category: "banking-financial", detail: "Retail and corporate banking", bucket: "growth", tier: "Good", pe: 18.4, roe: 10.5, debt: "N/A (Bank)", growth5Y: "24.1%" },
    { name: "Indian Bank", category: "banking-financial", detail: "Public-sector banking", bucket: "turnaround", tier: "Good", pe: 7.4, roe: 16.9, debt: "N/A (Bank)", growth5Y: "15.8%" },
    { name: "Indian Overseas Bank", category: "banking-financial", detail: "Public-sector banking", bucket: "turnaround", tier: "Average", pe: 24.1, roe: 9.8, debt: "N/A (Bank)", growth5Y: "10.1%" },
    { name: "IndusInd Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "turnaround", tier: "Average", pe: 12.1, roe: 14.5, debt: "N/A (Bank)", growth5Y: "13.4%" },
    { name: "Jammu & Kashmir Bank", category: "banking-financial", detail: "Banking", bucket: "turnaround", tier: "Good", pe: 6.9, roe: 15.2, debt: "N/A (Bank)", growth5Y: "14.1%" },
    { name: "Karnataka Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "turnaround", tier: "Average", pe: 6.2, roe: 13.1, debt: "N/A (Bank)", growth5Y: "8.9%" },
    { name: "Karur Vysya Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "compounders", tier: "Strong", pe: 9.8, roe: 16.8, debt: "N/A (Bank)", growth5Y: "15.2%" },
    { name: "Kotak Mahindra Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "compounders", tier: "Strong", pe: 21.4, roe: 14.9, debt: "N/A (Bank)", growth5Y: "15.6%" },
    { name: "LIC", category: "banking-financial", detail: "Life insurance", bucket: "turnaround", tier: "Good", pe: 14.8, roe: 80.5, debt: "Zero", growth5Y: "12.8%" },
    { name: "LIC Housing Finance", category: "banking-financial", detail: "Housing finance", bucket: "turnaround", tier: "Good", pe: 7.9, roe: 14.2, debt: "High", growth5Y: "9.5%" },
    { name: "Mahindra & Mahindra Financial Services", category: "banking-financial", detail: "Vehicle and rural finance", bucket: "cyclical", tier: "Average", pe: 17.5, roe: 11.2, debt: "High", growth5Y: "11.8%" },
    { name: "Manappuram Finance", category: "banking-financial", detail: "Gold and other lending", bucket: "cyclical", tier: "Good", pe: 7.8, roe: 18.4, debt: "Moderate", growth5Y: "14.6%" },
    { name: "Muthoot Finance", category: "banking-financial", detail: "Gold loans", bucket: "compounders", tier: "Strong", pe: 15.2, roe: 20.8, debt: "Moderate", growth5Y: "16.9%" },
    { name: "PNB", category: "banking-financial", detail: "Public-sector banking", bucket: "turnaround", tier: "Average", pe: 9.5, roe: 11.4, debt: "N/A (Bank)", growth5Y: "12.5%" },
    { name: "Punjab & Sind Bank", category: "banking-financial", detail: "Public-sector banking", bucket: "turnaround", tier: "Risky", pe: 35.2, roe: 4.8, debt: "N/A (Bank)", growth5Y: "3.2%" },
    { name: "RBL Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "turnaround", tier: "Average", pe: 11.2, roe: 8.9, debt: "N/A (Bank)", growth5Y: "7.8%" },
    { name: "REC", category: "banking-financial", detail: "Infrastructure financing", bucket: "turnaround", tier: "Strong", pe: 7.1, roe: 21.5, debt: "High", growth5Y: "18.4%" },
    { name: "SBI", category: "banking-financial", detail: "Banking and financial services", bucket: "turnaround", tier: "Strong", pe: 10.4, roe: 18.1, debt: "N/A (Bank)", growth5Y: "19.5%" },
    { name: "SBI Cards", category: "banking-financial", detail: "Credit cards", bucket: "growth", tier: "Average", pe: 28.5, roe: 22.1, debt: "Moderate", growth5Y: "17.4%" },
    { name: "SBI Life", category: "banking-financial", detail: "Life insurance", bucket: "compounders", tier: "Strong", pe: 78.4, roe: 14.5, debt: "Zero", growth5Y: "16.2%" },
    { name: "Shriram Finance", category: "banking-financial", detail: "Commercial vehicle and consumer finance", bucket: "compounders", tier: "Strong", pe: 13.8, roe: 16.4, debt: "Moderate", growth5Y: "18.9%" },
    { name: "UCO Bank", category: "banking-financial", detail: "Public-sector banking", bucket: "turnaround", tier: "Average", pe: 22.4, roe: 9.4, debt: "N/A (Bank)", growth5Y: "8.9%" },
    { name: "Union Bank of India", category: "banking-financial", detail: "Public-sector banking", bucket: "turnaround", tier: "Good", pe: 6.9, roe: 16.4, debt: "N/A (Bank)", growth5Y: "16.1%" },
    { name: "UTI AMC", category: "banking-financial", detail: "Asset management", bucket: "turnaround", tier: "Good", pe: 21.5, roe: 14.8, debt: "Zero", growth5Y: "11.2%" },
    { name: "Yes Bank", category: "banking-financial", detail: "Private-sector banking", bucket: "turnaround", tier: "Risky", pe: 55.4, roe: 3.2, debt: "N/A (Bank)", growth5Y: "4.5%" },
    { name: "Angel One", category: "banking-financial", detail: "Stock broking and investment services", bucket: "growth", tier: "Strong", pe: 19.8, roe: 38.5, debt: "Low", growth5Y: "34.2%" },
    { name: "BSE", category: "banking-financial", detail: "Stock exchange", bucket: "growth", tier: "Strong", pe: 45.2, roe: 28.4, debt: "Zero", growth5Y: "28.9%" },
    { name: "CDSL", category: "banking-financial", detail: "Securities depository", bucket: "compounders", tier: "Strong", pe: 52.1, roe: 31.5, debt: "Zero", growth5Y: "27.4%" },
    { name: "CAMS", category: "banking-financial", detail: "Mutual-fund transaction services", bucket: "compounders", tier: "Strong", pe: 46.8, roe: 39.8, debt: "Zero", growth5Y: "19.5%" },
    { name: "Computer Age Management Services", category: "banking-financial", detail: "Financial infrastructure", bucket: "compounders", tier: "Strong", pe: 46.8, roe: 39.8, debt: "Zero", growth5Y: "19.5%" },
    { name: "CreditAccess Grameen", category: "banking-financial", detail: "Microfinance", bucket: "growth", tier: "Strong", pe: 14.8, roe: 20.5, debt: "Moderate", growth5Y: "24.6%" },
    { name: "Five-Star Business Finance", category: "banking-financial", detail: "Small-business loans", bucket: "growth", tier: "Strong", pe: 24.2, roe: 18.9, debt: "Moderate", growth5Y: "26.1%" },
    { name: "Home First Finance", category: "banking-financial", detail: "Affordable housing finance", bucket: "growth", tier: "Strong", pe: 28.5, roe: 16.5, debt: "Moderate", growth5Y: "27.8%" },
    { name: "Aavas Financiers", category: "banking-financial", detail: "Housing finance", bucket: "growth", tier: "Good", pe: 24.1, roe: 14.2, debt: "Moderate", growth5Y: "19.4%" },
    { name: "Aptus Value Housing Finance", category: "banking-financial", detail: "Housing finance", bucket: "growth", tier: "Strong", pe: 22.8, roe: 17.5, debt: "Moderate", growth5Y: "25.2%" },
    { name: "Can Fin Homes", category: "banking-financial", detail: "Housing finance", bucket: "compounders", tier: "Strong", pe: 12.8, roe: 18.2, debt: "Moderate", growth5Y: "16.1%" },
    { name: "PNB Housing Finance", category: "banking-financial", detail: "Housing finance", bucket: "turnaround", tier: "Good", pe: 16.4, roe: 11.5, debt: "Moderate", growth5Y: "13.2%" },
    { name: "IIFL Finance", category: "banking-financial", detail: "Retail and business finance", bucket: "turnaround", tier: "Risky", pe: 12.8, roe: 14.1, debt: "High", growth5Y: "15.4%" },
    { name: "IIFL Capital Services", category: "banking-financial", detail: "Capital-market services", bucket: "growth", tier: "Good", pe: 16.5, roe: 22.4, debt: "Low", growth5Y: "21.0%" },
    { name: "JM Financial", category: "banking-financial", detail: "Investment banking and financial services", bucket: "cyclical", tier: "Average", pe: 15.2, roe: 9.8, debt: "Moderate", growth5Y: "8.5%" },
    { name: "Motilal Oswal Financial Services", category: "banking-financial", detail: "Broking, wealth and asset management", bucket: "growth", tier: "Strong", pe: 17.8, roe: 28.9, debt: "Low", growth5Y: "29.4%" },
    { name: "Nuvama Wealth Management", category: "banking-financial", detail: "Wealth management", bucket: "growth", tier: "Strong", pe: 25.4, roe: 21.2, debt: "Low", growth5Y: "22.5%" },
    { name: "Edelweiss Financial Services", category: "banking-financial", detail: "Financial services", bucket: "turnaround", tier: "Average", pe: 18.2, roe: 7.2, debt: "High", growth5Y: "5.1%" },
    { name: "Anand Rathi Wealth", category: "banking-financial", detail: "Wealth management", bucket: "growth", tier: "Strong", pe: 42.1, roe: 41.2, debt: "Zero", growth5Y: "31.5%" },
    { name: "Prudent Corporate Advisory", category: "banking-financial", detail: "Mutual-fund distribution", bucket: "growth", tier: "Strong", pe: 48.5, roe: 32.4, debt: "Zero", growth5Y: "28.4%" },
    { name: "Nippon Life India AMC", category: "banking-financial", detail: "Asset management", bucket: "compounders", tier: "Strong", pe: 33.2, roe: 27.5, debt: "Zero", growth5Y: "18.2%" },
    { name: "Aditya Birla Capital", category: "banking-financial", detail: "Financial-services holding company", bucket: "turnaround", tier: "Good", pe: 18.4, roe: 13.8, debt: "High", growth5Y: "17.9%" },
    { name: "Aditya Birla Sun Life AMC", category: "banking-financial", detail: "Asset management", bucket: "compounders", tier: "Good", pe: 22.4, roe: 24.1, debt: "Zero", growth5Y: "10.4%" },
    { name: "Bajaj Housing Finance", category: "banking-financial", detail: "Housing finance", bucket: "growth", tier: "Strong", pe: 55.0, roe: 15.2, debt: "Moderate", growth5Y: "32.0%" },
    { name: "Bajaj Holdings & Investment", category: "banking-financial", detail: "Investment holding company", bucket: "compounders", tier: "Strong", pe: 14.2, roe: 12.8, debt: "Zero", growth5Y: "14.5%" },
    { name: "Poonawalla Fincorp", category: "banking-financial", detail: "Consumer and business finance", bucket: "growth", tier: "Strong", pe: 19.5, roe: 16.4, debt: "Moderate", growth5Y: "35.1%" },
    { name: "Sundaram Finance", category: "banking-financial", detail: "Vehicle and business finance", bucket: "compounders", tier: "Strong", pe: 32.5, roe: 16.5, debt: "Moderate", growth5Y: "14.8%" },
    { name: "Sundaram Finance Holdings", category: "banking-financial", detail: "Financial holding company", bucket: "compounders", tier: "Good", pe: 24.1, roe: 11.2, debt: "Zero", growth5Y: "12.1%" },
    { name: "Shriram Capital", category: "banking-financial", detail: "Financial-services holding", bucket: "turnaround", tier: "Good", pe: 14.5, roe: 15.8, debt: "Moderate", growth5Y: "16.2%" },
    { name: "MAS Financial Services", category: "banking-financial", detail: "MSME finance", bucket: "growth", tier: "Good", pe: 18.2, roe: 15.6, debt: "Moderate", growth5Y: "18.5%" },
    { name: "Muthoot Microfin", category: "banking-financial", detail: "Microfinance", bucket: "growth", tier: "Average", pe: 12.4, roe: 18.1, debt: "Moderate", growth5Y: "21.4%" },
    { name: "Ugro Capital", category: "banking-financial", detail: "MSME lending", bucket: "growth", tier: "Good", pe: 22.1, roe: 10.8, debt: "Moderate", growth5Y: "45.0%" },
    { name: "Utkarsh Small Finance Bank", category: "banking-financial", detail: "Banking", bucket: "growth", tier: "Average", pe: 11.5, roe: 17.2, debt: "N/A (Bank)", growth5Y: "22.1%" },
    { name: "ESAF Small Finance Bank", category: "banking-financial", detail: "Banking", bucket: "growth", tier: "Risky", pe: 9.8, roe: 14.5, debt: "N/A (Bank)", growth5Y: "16.8%" },
    { name: "Jana Small Finance Bank", category: "banking-financial", detail: "Banking", bucket: "turnaround", tier: "Good", pe: 10.4, roe: 16.8, debt: "N/A (Bank)", growth5Y: "19.2%" },
    { name: "Fusion Finance", category: "banking-financial", detail: "Microfinance", bucket: "turnaround", tier: "Risky", pe: 11.8, roe: 15.4, debt: "Moderate", growth5Y: "18.9%" },
    { name: "Star Health Insurance", category: "banking-financial", detail: "Health insurance", bucket: "growth", tier: "Average", pe: 35.2, roe: 12.4, debt: "Zero", growth5Y: "19.8%" },
    { name: "General Insurance Corporation", category: "banking-financial", detail: "Reinsurance", bucket: "turnaround", tier: "Good", pe: 8.5, roe: 14.2, debt: "Zero", growth5Y: "11.5%" },
    { name: "New India Assurance", category: "banking-financial", detail: "General insurance", bucket: "turnaround", tier: "Average", pe: 28.4, roe: 5.2, debt: "Zero", growth5Y: "6.8%" },
    { name: "Go Digit General Insurance", category: "banking-financial", detail: "General insurance", bucket: "high-risk", tier: "Risky", pe: 72.0, roe: 8.5, debt: "Zero", growth5Y: "38.5%" },
    { name: "ICICI Securities", category: "banking-financial", detail: "Broking/investment services", bucket: "compounders", tier: "Strong", pe: 16.8, roe: 45.2, debt: "Low", growth5Y: "17.5%" },
    { name: "IREDA", category: "banking-financial", detail: "Renewable-energy financing", bucket: "growth", tier: "Strong", pe: 34.2, roe: 15.8, debt: "High", growth5Y: "31.2%" },
    { name: "IRFC", category: "banking-financial", detail: "Railway financing", bucket: "turnaround", tier: "Good", pe: 28.5, roe: 13.2, debt: "High", growth5Y: "16.4%" },
    { name: "HUDCO", category: "banking-financial", detail: "Housing/infrastructure finance", bucket: "turnaround", tier: "Good", pe: 18.2, roe: 14.1, debt: "High", growth5Y: "14.8%" },

    // 2. Capital Goods, Engineering & Industrial Manufacturing
    { name: "ABB India", category: "capital-goods", detail: "Electrical equipment and automation", bucket: "compounders", tier: "Strong", pe: 82.5, roe: 22.4, debt: "Zero", growth5Y: "21.4%" },
    { name: "AIA Engineering", category: "capital-goods", detail: "Industrial grinding equipment", bucket: "compounders", tier: "Strong", pe: 28.4, roe: 19.8, debt: "Zero", growth5Y: "14.5%" },
    { name: "BHEL", category: "capital-goods", detail: "Power and industrial equipment", bucket: "turnaround", tier: "Average", pe: 95.0, roe: 2.1, debt: "Low", growth5Y: "4.2%" },
    { name: "Bharat Electronics", category: "capital-goods", detail: "Defence electronics", bucket: "growth", tier: "Strong", pe: 42.1, roe: 26.5, debt: "Zero", growth5Y: "18.9%" },
    { name: "CG Power", category: "capital-goods", detail: "Electrical equipment", bucket: "turnaround", tier: "Strong", pe: 74.2, roe: 32.1, debt: "Zero", growth5Y: "28.5%" },
    { name: "Cummins India", category: "capital-goods", detail: "Engines and power systems", bucket: "compounders", tier: "Strong", pe: 44.8, roe: 21.5, debt: "Zero", growth5Y: "16.8%" },
    { name: "Siemens", category: "capital-goods", detail: "Industrial automation and electrical equipment", bucket: "compounders", tier: "Strong", pe: 75.6, roe: 18.9, debt: "Zero", growth5Y: "19.2%" },
    { name: "Schneider Electric Infrastructure", category: "capital-goods", detail: "Power equipment", bucket: "growth", tier: "Strong", pe: 62.4, roe: 38.2, debt: "Low", growth5Y: "24.5%" },
    { name: "Thermax", category: "capital-goods", detail: "Energy and environmental equipment", bucket: "compounders", tier: "Good", pe: 58.9, roe: 14.2, debt: "Zero", growth5Y: "15.1%" },
    { name: "Honeywell Automation", category: "capital-goods", detail: "Industrial automation", bucket: "compounders", tier: "Strong", pe: 52.4, roe: 16.5, debt: "Zero", growth5Y: "11.4%" },
    { name: "Hitachi Energy India", category: "capital-goods", detail: "Power-grid equipment", bucket: "growth", tier: "Strong", pe: 110.0, roe: 14.8, debt: "Low", growth5Y: "22.1%" },
    { name: "GE Vernova T&D India", category: "capital-goods", detail: "Electricity transmission equipment", bucket: "growth", tier: "Strong", pe: 68.4, roe: 24.1, debt: "Zero", growth5Y: "26.4%" },
    { name: "Larsen & Toubro", category: "capital-goods", detail: "Engineering, construction and infrastructure", bucket: "cyclical", tier: "Strong", pe: 31.4, roe: 15.8, debt: "Moderate", growth5Y: "14.2%" },
    { name: "Engineers India", category: "capital-goods", detail: "Engineering consultancy", bucket: "turnaround", tier: "Good", pe: 24.5, roe: 18.2, debt: "Zero", growth5Y: "9.8%" },
    { name: "RITES", category: "capital-goods", detail: "Engineering and transport consultancy", bucket: "compounders", tier: "Good", pe: 22.1, roe: 21.4, debt: "Zero", growth5Y: "8.9%" },
    { name: "Rail Vikas Nigam", category: "capital-goods", detail: "Railway infrastructure", bucket: "growth", tier: "Strong", pe: 52.4, roe: 17.5, debt: "Moderate", growth5Y: "21.8%" },
    { name: "IRCON International", category: "capital-goods", detail: "Railway and infrastructure construction", bucket: "turnaround", tier: "Good", pe: 21.4, roe: 16.2, debt: "Low", growth5Y: "16.4%" },
    { name: "NBCC", category: "capital-goods", detail: "Government construction and EPC", bucket: "turnaround", tier: "Good", pe: 58.2, roe: 22.4, debt: "Zero", growth5Y: "14.1%" },
    { name: "Cochin Shipyard", category: "capital-goods", detail: "Shipbuilding and repair", bucket: "growth", tier: "Strong", pe: 48.9, roe: 18.9, debt: "Zero", growth5Y: "25.4%" },
    { name: "Garden Reach Shipbuilders", category: "capital-goods", detail: "Naval shipbuilding", bucket: "growth", tier: "Strong", pe: 42.5, roe: 24.5, debt: "Zero", growth5Y: "29.1%" },
    { name: "Mazagon Dock Shipbuilders", category: "capital-goods", detail: "Warships and submarines", bucket: "growth", tier: "Strong", pe: 35.8, roe: 34.2, debt: "Zero", growth5Y: "32.5%" },
    { name: "Bharat Dynamics", category: "capital-goods", detail: "Missiles and defence systems", bucket: "growth", tier: "Strong", pe: 65.4, roe: 16.8, debt: "Zero", growth5Y: "17.9%" },
    { name: "Hindustan Aeronautics", category: "capital-goods", detail: "Military and civilian aircraft", bucket: "growth", tier: "Strong", pe: 36.2, roe: 28.5, debt: "Zero", growth5Y: "23.4%" },
    { name: "Solar Industries", category: "capital-goods", detail: "Explosives and defence products", bucket: "compounders", tier: "Strong", pe: 84.1, roe: 26.8, debt: "Low", growth5Y: "27.5%" },
    { name: "Data Patterns", category: "capital-goods", detail: "Defence electronics", bucket: "growth", tier: "Strong", pe: 54.2, roe: 17.4, debt: "Zero", growth5Y: "31.2%" },
    { name: "Astra Microwave", category: "capital-goods", detail: "Defence electronics", bucket: "growth", tier: "Good", pe: 42.1, roe: 16.2, debt: "Low", growth5Y: "19.5%" },
    { name: "MTAR Technologies", category: "capital-goods", detail: "Precision engineering", bucket: "growth", tier: "Average", pe: 58.4, roe: 12.8, debt: "Low", growth5Y: "22.4%" },
    { name: "Kaynes Technology", category: "capital-goods", detail: "Electronics manufacturing", bucket: "growth", tier: "Strong", pe: 92.5, roe: 16.9, debt: "Low", growth5Y: "48.2%" },
    { name: "Dixon Technologies", category: "capital-goods", detail: "Electronics manufacturing", bucket: "growth", tier: "Strong", pe: 105.0, roe: 25.4, debt: "Low", growth5Y: "42.1%" },
    { name: "Syrma SGS Technology", category: "capital-goods", detail: "Electronics manufacturing", bucket: "growth", tier: "Good", pe: 48.5, roe: 11.2, debt: "Low", growth5Y: "28.4%" },
    { name: "Polycab India", category: "capital-goods", detail: "Wires and cables", bucket: "compounders", tier: "Strong", pe: 45.2, roe: 24.8, debt: "Zero", growth5Y: "22.9%" },
    { name: "KEI Industries", category: "capital-goods", detail: "Wires and cables", bucket: "compounders", tier: "Strong", pe: 52.1, roe: 21.2, debt: "Zero", growth5Y: "18.5%" },
    { name: "Havells India", category: "capital-goods", detail: "Electrical consumer products", bucket: "compounders", tier: "Strong", pe: 68.4, roe: 20.5, debt: "Zero", growth5Y: "16.4%" },
    { name: "Finolex Cables", category: "capital-goods", detail: "Cables and electrical products", bucket: "compounders", tier: "Good", pe: 24.5, roe: 13.8, debt: "Zero", growth5Y: "11.2%" },
    { name: "Apar Industries", category: "capital-goods", detail: "Conductors and specialty oils", bucket: "growth", tier: "Strong", pe: 34.2, roe: 28.9, debt: "Low", growth5Y: "26.4%" },
    { name: "V-Guard Industries", category: "capital-goods", detail: "Electrical appliances", bucket: "compounders", tier: "Good", pe: 48.1, roe: 16.4, debt: "Low", growth5Y: "14.8%" },
    { name: "KEC International", category: "capital-goods", detail: "Power and infrastructure EPC", bucket: "cyclical", tier: "Good", pe: 38.5, roe: 12.1, debt: "Moderate", growth5Y: "13.5%" },
    { name: "Kalpataru Projects", category: "capital-goods", detail: "Power and infrastructure EPC", bucket: "cyclical", tier: "Good", pe: 32.1, roe: 13.5, debt: "Moderate", growth5Y: "15.8%" },
    { name: "Sterling & Wilson Renewable Energy", category: "capital-goods", detail: "Solar EPC", bucket: "high-risk", tier: "Risky", pe: 85.0, roe: -5.2, debt: "Moderate", growth5Y: "12.4%" },
    { name: "Inox Wind", category: "capital-goods", detail: "Wind turbines", bucket: "turnaround", tier: "Good", pe: 42.0, roe: 14.2, debt: "Low", growth5Y: "35.0%" },
    { name: "Suzlon Energy", category: "capital-goods", detail: "Wind turbines", bucket: "high-risk", tier: "Good", pe: 72.4, roe: 25.1, debt: "Zero", growth5Y: "38.9%" },
    { name: "Blue Star", category: "capital-goods", detail: "Air-conditioning systems", bucket: "growth", tier: "Strong", pe: 64.2, roe: 22.8, debt: "Low", growth5Y: "18.2%" },
    { name: "Voltas", category: "capital-goods", detail: "Air conditioning and engineering", bucket: "compounders", tier: "Good", pe: 68.9, roe: 8.9, debt: "Zero", growth5Y: "12.1%" },
    { name: "Ratnamani Metals", category: "capital-goods", detail: "Industrial pipes", bucket: "compounders", tier: "Strong", pe: 35.4, roe: 21.2, debt: "Zero", growth5Y: "17.8%" },
    { name: "Welspun Corp", category: "capital-goods", detail: "Large-diameter pipes", bucket: "cyclical", tier: "Good", pe: 18.2, roe: 18.5, debt: "Low", growth5Y: "19.2%" },
    { name: "APL Apollo Tubes", category: "capital-goods", detail: "Steel tubes", bucket: "compounders", tier: "Strong", pe: 54.1, roe: 23.5, debt: "Low", growth5Y: "24.1%" },
    { name: "Jindal Saw", category: "capital-goods", detail: "Pipes", bucket: "cyclical", tier: "Good", pe: 12.8, roe: 19.4, debt: "Moderate", growth5Y: "21.5%" },
    { name: "Praj Industries", category: "capital-goods", detail: "Ethanol and bioenergy equipment", bucket: "growth", tier: "Good", pe: 42.5, roe: 22.1, debt: "Zero", growth5Y: "22.4%" },
    { name: "Triveni Turbine", category: "capital-goods", detail: "Industrial steam turbines", bucket: "compounders", tier: "Strong", pe: 58.2, roe: 27.4, debt: "Zero", growth5Y: "20.1%" },
    { name: "Power Mech Projects", category: "capital-goods", detail: "Power-plant construction", bucket: "growth", tier: "Good", pe: 28.4, roe: 17.8, debt: "Low", growth5Y: "21.8%" },
    { name: "Techno Electric", category: "capital-goods", detail: "Power infrastructure", bucket: "growth", tier: "Good", pe: 38.2, roe: 16.5, debt: "Zero", growth5Y: "18.4%" },
    { name: "NCC", category: "capital-goods", detail: "Construction and infrastructure", bucket: "cyclical", tier: "Good", pe: 18.5, roe: 12.4, debt: "Low", growth5Y: "15.2%" },
    { name: "HG Infra Engineering", category: "capital-goods", detail: "Roads and infrastructure", bucket: "growth", tier: "Strong", pe: 14.2, roe: 22.1, debt: "Low", growth5Y: "24.8%" },
    { name: "Ashoka Buildcon", category: "capital-goods", detail: "Roads and infrastructure", bucket: "turnaround", tier: "Good", pe: 11.2, roe: 18.5, debt: "Moderate", growth5Y: "16.2%" },
    { name: "KNR Constructions", category: "capital-goods", detail: "Roads and infrastructure", bucket: "compounders", tier: "Strong", pe: 14.8, roe: 19.4, debt: "Zero", growth5Y: "17.1%" },
    { name: "PNC Infratech", category: "capital-goods", detail: "Roads and infrastructure", bucket: "compounders", tier: "Strong", pe: 12.5, roe: 18.2, debt: "Low", growth5Y: "16.8%" },
    { name: "Titagarh Rail Systems", category: "capital-goods", detail: "Railway wagons and trains", bucket: "growth", tier: "Strong", pe: 58.4, roe: 20.4, debt: "Low", growth5Y: "32.1%" },
    { name: "Jupiter Wagons", category: "capital-goods", detail: "Railway freight equipment", bucket: "growth", tier: "Strong", pe: 44.2, roe: 24.1, debt: "Low", growth5Y: "38.5%" },
    { name: "BEML", category: "capital-goods", detail: "Defence, rail and heavy equipment", bucket: "turnaround", tier: "Good", pe: 52.1, roe: 10.2, debt: "Low", growth5Y: "12.4%" },
    { name: "TRF", category: "capital-goods", detail: "Material-handling equipment", bucket: "turnaround", tier: "Risky", pe: 25.4, roe: -4.5, debt: "High", growth5Y: "3.2%" },
    { name: "Elgi Equipments", category: "capital-goods", detail: "Industrial compressors", bucket: "compounders", tier: "Strong", pe: 51.2, roe: 21.8, debt: "Zero", growth5Y: "16.9%" },

    // 3. Healthcare & Pharmaceuticals
    { name: "Sun Pharma", category: "healthcare-pharma", detail: "Medicines", bucket: "compounders", tier: "Strong", pe: 36.5, roe: 16.8, debt: "Zero", growth5Y: "12.8%" },
    { name: "Dr. Reddy's Labs", category: "healthcare-pharma", detail: "Generic medicines", bucket: "compounders", tier: "Strong", pe: 19.4, roe: 20.5, debt: "Zero", growth5Y: "14.2%" },
    { name: "Cipla", category: "healthcare-pharma", detail: "Medicines", bucket: "compounders", tier: "Strong", pe: 28.2, roe: 16.2, debt: "Zero", growth5Y: "11.5%" },
    { name: "Lupin", category: "healthcare-pharma", detail: "Generic and specialty medicines", bucket: "turnaround", tier: "Good", pe: 38.5, roe: 13.8, debt: "Low", growth5Y: "9.8%" },
    { name: "Aurobindo Pharma", category: "healthcare-pharma", detail: "Generic medicines", bucket: "turnaround", tier: "Good", pe: 21.4, roe: 13.2, debt: "Zero", growth5Y: "10.4%" },
    { name: "Divi's Laboratories", category: "healthcare-pharma", detail: "APIs and pharmaceutical ingredients", bucket: "compounders", tier: "Strong", pe: 72.4, roe: 13.9, debt: "Zero", growth5Y: "13.1%" },
    { name: "Zydus Lifesciences", category: "healthcare-pharma", detail: "Medicines and vaccines", bucket: "compounders", tier: "Strong", pe: 27.8, roe: 21.4, debt: "Zero", growth5Y: "15.4%" },
    { name: "Torrent Pharmaceuticals", category: "healthcare-pharma", detail: "Medicines", bucket: "compounders", tier: "Strong", pe: 58.4, roe: 28.5, debt: "Low", growth5Y: "13.9%" },
    { name: "Alkem Laboratories", category: "healthcare-pharma", detail: "Medicines", bucket: "compounders", tier: "Strong", pe: 34.2, roe: 17.8, debt: "Zero", growth5Y: "12.4%" },
    { name: "Mankind Pharma", category: "healthcare-pharma", detail: "Pharmaceutical and consumer healthcare", bucket: "growth", tier: "Strong", pe: 48.5, roe: 22.4, debt: "Zero", growth5Y: "18.5%" },
    { name: "Glenmark Pharma", category: "healthcare-pharma", detail: "Medicines", bucket: "turnaround", tier: "Good", pe: 42.1, roe: 11.5, debt: "Low", growth5Y: "8.9%" },
    { name: "Laurus Labs", category: "healthcare-pharma", detail: "APIs and pharmaceuticals", bucket: "cyclical", tier: "Average", pe: 85.0, roe: 5.8, debt: "Moderate", growth5Y: "16.2%" },
    { name: "Natco Pharma", category: "healthcare-pharma", detail: "Specialty medicines", bucket: "growth", tier: "Strong", pe: 18.4, roe: 24.1, debt: "Zero", growth5Y: "19.8%" },
    { name: "Ipca Laboratories", category: "healthcare-pharma", detail: "Pharmaceutical products", bucket: "compounders", tier: "Good", pe: 52.1, roe: 12.5, debt: "Low", growth5Y: "11.2%" },
    { name: "JB Chemicals", category: "healthcare-pharma", detail: "Medicines", bucket: "compounders", tier: "Strong", pe: 45.2, roe: 21.8, debt: "Zero", growth5Y: "16.8%" },
    { name: "Ajanta Pharma", category: "healthcare-pharma", detail: "Specialty pharmaceuticals", bucket: "compounders", tier: "Strong", pe: 41.2, roe: 24.5, debt: "Zero", growth5Y: "14.9%" },
    { name: "Eris Lifesciences", category: "healthcare-pharma", detail: "Chronic-care medicines", bucket: "growth", tier: "Good", pe: 38.4, roe: 18.2, debt: "Low", growth5Y: "15.1%" },
    { name: "Alembic Pharmaceuticals", category: "healthcare-pharma", detail: "Medicines", bucket: "turnaround", tier: "Average", pe: 32.1, roe: 12.4, debt: "Low", growth5Y: "7.8%" },
    { name: "Granules India", category: "healthcare-pharma", detail: "Pharmaceutical ingredients", bucket: "growth", tier: "Good", pe: 28.5, roe: 14.8, debt: "Low", growth5Y: "14.2%" },
    { name: "Biocon", category: "healthcare-pharma", detail: "Biopharmaceuticals", bucket: "turnaround", tier: "Average", pe: 42.0, roe: 6.2, debt: "High", growth5Y: "12.1%" },
    { name: "Biocon Biologics", category: "healthcare-pharma", detail: "Biosimilars", bucket: "growth", tier: "Good", pe: 38.0, roe: 8.5, debt: "High", growth5Y: "21.0%" },
    { name: "Syngene International", category: "healthcare-pharma", detail: "Drug research and development", bucket: "compounders", tier: "Strong", pe: 54.2, roe: 14.2, debt: "Zero", growth5Y: "15.8%" },
    { name: "Max Healthcare", category: "healthcare-pharma", detail: "Hospitals", bucket: "growth", tier: "Strong", pe: 78.4, roe: 16.8, debt: "Zero", growth5Y: "24.5%" },
    { name: "Apollo Hospitals", category: "healthcare-pharma", detail: "Hospitals and healthcare", bucket: "compounders", tier: "Strong", pe: 65.2, roe: 15.2, debt: "Low", growth5Y: "16.4%" },
    { name: "Fortis Healthcare", category: "healthcare-pharma", detail: "Hospitals", bucket: "turnaround", tier: "Strong", pe: 62.1, roe: 9.8, debt: "Low", growth5Y: "18.2%" },
    { name: "Narayana Hrudayalaya", category: "healthcare-pharma", detail: "Hospitals", bucket: "compounders", tier: "Strong", pe: 36.4, roe: 28.4, debt: "Low", growth5Y: "19.5%" },
    { name: "Global Health", category: "healthcare-pharma", detail: "Hospitals", bucket: "growth", tier: "Strong", pe: 54.1, roe: 19.5, debt: "Zero", growth5Y: "25.1%" },
    { name: "Aster DM Healthcare", category: "healthcare-pharma", detail: "Hospitals", bucket: "turnaround", tier: "Good", pe: 32.5, roe: 14.1, debt: "Zero", growth5Y: "15.4%" },
    { name: "KIMS", category: "healthcare-pharma", detail: "Hospitals", bucket: "growth", tier: "Strong", pe: 48.2, roe: 22.1, debt: "Low", growth5Y: "22.8%" },
    { name: "Rainbow Children's Medicare", category: "healthcare-pharma", detail: "Children's hospitals", bucket: "growth", tier: "Strong", pe: 52.4, roe: 18.5, debt: "Zero", growth5Y: "21.4%" },
    { name: "Medanta", category: "healthcare-pharma", detail: "Hospitals", bucket: "growth", tier: "Strong", pe: 54.1, roe: 19.5, debt: "Zero", growth5Y: "25.1%" },
    { name: "Dr Lal PathLabs", category: "healthcare-pharma", detail: "Diagnostics", bucket: "compounders", tier: "Good", pe: 64.2, roe: 22.4, debt: "Zero", growth5Y: "14.2%" },
    { name: "Metropolis Healthcare", category: "healthcare-pharma", detail: "Diagnostics", bucket: "compounders", tier: "Good", pe: 58.1, roe: 18.9, debt: "Zero", growth5Y: "13.1%" },
    { name: "Vijaya Diagnostic Centre", category: "healthcare-pharma", detail: "Diagnostics", bucket: "growth", tier: "Strong", pe: 54.2, roe: 20.4, debt: "Zero", growth5Y: "18.5%" },
    { name: "Thyrocare Technologies", category: "healthcare-pharma", detail: "Diagnostics", bucket: "turnaround", tier: "Good", pe: 42.1, roe: 16.5, debt: "Zero", growth5Y: "9.5%" },
    { name: "Healthcare Global", category: "healthcare-pharma", detail: "Cancer hospitals", bucket: "growth", tier: "Good", pe: 68.5, roe: 7.8, debt: "Moderate", growth5Y: "17.4%" },
    { name: "Yatharth Hospital", category: "healthcare-pharma", detail: "Hospitals", bucket: "growth", tier: "Strong", pe: 38.2, roe: 21.4, debt: "Zero", growth5Y: "29.5%" },
    { name: "Jupiter Life Line Hospitals", category: "healthcare-pharma", detail: "Hospitals", bucket: "growth", tier: "Strong", pe: 46.1, roe: 18.2, debt: "Zero", growth5Y: "24.1%" },
    { name: "Arvind Remedies", category: "healthcare-pharma", detail: "Pharmaceuticals", bucket: "high-risk", tier: "Risky", pe: 15.0, roe: -2.1, debt: "High", growth5Y: "-1.2%" },
    { name: "Marksans Pharma", category: "healthcare-pharma", detail: "Generic medicines", bucket: "growth", tier: "Strong", pe: 25.4, roe: 18.9, debt: "Zero", growth5Y: "19.2%" },
    { name: "Neuland Laboratories", category: "healthcare-pharma", detail: "APIs", bucket: "growth", tier: "Strong", pe: 42.1, roe: 28.5, debt: "Zero", growth5Y: "26.4%" },
    { name: "Suven Pharma", category: "healthcare-pharma", detail: "Pharmaceutical ingredients", bucket: "growth", tier: "Strong", pe: 58.4, roe: 22.1, debt: "Zero", growth5Y: "18.9%" },
    { name: "Piramal Pharma", category: "healthcare-pharma", detail: "Contract manufacturing and medicines", bucket: "turnaround", tier: "Good", pe: 75.0, roe: 2.5, debt: "Moderate", growth5Y: "14.1%" },
    { name: "Emcure Pharmaceuticals", category: "healthcare-pharma", detail: "Medicines", bucket: "growth", tier: "Strong", pe: 36.2, roe: 19.4, debt: "Low", growth5Y: "17.8%" },
    { name: "FDC", category: "healthcare-pharma", detail: "Pharmaceutical products", bucket: "compounders", tier: "Good", pe: 28.4, roe: 15.2, debt: "Zero", growth5Y: "10.5%" },
    { name: "Gland Pharma", category: "healthcare-pharma", detail: "Injectable medicines", bucket: "turnaround", tier: "Good", pe: 35.2, roe: 10.4, debt: "Zero", growth5Y: "12.8%" },
    { name: "Sanofi India", category: "healthcare-pharma", detail: "Pharmaceutical products", bucket: "compounders", tier: "Good", pe: 32.1, roe: 26.4, debt: "Zero", growth5Y: "6.5%" },

    // 4. Automobiles & Auto Components
    { name: "Maruti Suzuki", category: "automobiles", detail: "Passenger cars", bucket: "compounders", tier: "Strong", pe: 28.5, roe: 16.8, debt: "Zero", growth5Y: "12.4%" },
    { name: "Mahindra & Mahindra", category: "automobiles", detail: "SUVs, tractors and commercial vehicles", bucket: "growth", tier: "Strong", pe: 29.4, roe: 18.9, debt: "Low", growth5Y: "18.5%" },
    { name: "Tata Motors", category: "automobiles", detail: "Cars and commercial vehicles", bucket: "turnaround", tier: "Strong", pe: 10.2, roe: 48.5, debt: "Moderate", growth5Y: "21.4%" },
    { name: "Bajaj Auto", category: "automobiles", detail: "Motorcycles and three-wheelers", bucket: "compounders", tier: "Strong", pe: 32.1, roe: 25.4, debt: "Zero", growth5Y: "14.2%" },
    { name: "Hero MotoCorp", category: "automobiles", detail: "Motorcycles and scooters", bucket: "compounders", tier: "Good", pe: 24.5, roe: 22.1, debt: "Zero", growth5Y: "8.9%" },
    { name: "TVS Motor", category: "automobiles", detail: "Motorcycles and scooters", bucket: "growth", tier: "Strong", pe: 58.4, roe: 28.9, debt: "Moderate", growth5Y: "22.4%" },
    { name: "Eicher Motors", category: "automobiles", detail: "Royal Enfield motorcycles and trucks", bucket: "compounders", tier: "Strong", pe: 34.2, roe: 24.8, debt: "Zero", growth5Y: "16.8%" },
    { name: "Ashok Leyland", category: "automobiles", detail: "Trucks and buses", bucket: "cyclical", tier: "Good", pe: 25.1, roe: 22.4, debt: "Low", growth5Y: "15.2%" },
    { name: "Force Motors", category: "automobiles", detail: "Commercial vehicles", bucket: "growth", tier: "Strong", pe: 32.4, roe: 21.5, debt: "Low", growth5Y: "26.4%" },
    { name: "Bharat Forge", category: "automobiles", detail: "Forged automotive components", bucket: "growth", tier: "Strong", pe: 48.5, roe: 15.2, debt: "Low", growth5Y: "18.9%" },
    { name: "Bosch", category: "automobiles", detail: "Auto components and technology", bucket: "compounders", tier: "Strong", pe: 46.2, roe: 17.4, debt: "Zero", growth5Y: "13.5%" },
    { name: "Motherson", category: "automobiles", detail: "Automotive components", bucket: "growth", tier: "Strong", pe: 35.8, roe: 16.5, debt: "Moderate", growth5Y: "19.8%" },
    { name: "Samvardhana Motherson", category: "automobiles", detail: "Automotive systems", bucket: "growth", tier: "Strong", pe: 35.8, roe: 16.5, debt: "Moderate", growth5Y: "19.8%" },
    { name: "Uno Minda", category: "automobiles", detail: "Auto components", bucket: "growth", tier: "Strong", pe: 62.4, roe: 18.9, debt: "Low", growth5Y: "22.1%" },
    { name: "Sona BLW Precision Forgings", category: "automobiles", detail: "EV and drivetrain components", bucket: "growth", tier: "Strong", pe: 68.5, roe: 20.4, debt: "Zero", growth5Y: "29.4%" },
    { name: "Endurance Technologies", category: "automobiles", detail: "Auto components", bucket: "compounders", tier: "Strong", pe: 45.2, roe: 15.8, debt: "Zero", growth5Y: "14.2%" },
    { name: "Exide Industries", category: "automobiles", detail: "Batteries", bucket: "growth", tier: "Good", pe: 42.1, roe: 10.5, debt: "Zero", growth5Y: "11.8%" },
    { name: "Amara Raja Energy", category: "automobiles", detail: "Batteries", bucket: "growth", tier: "Strong", pe: 28.4, roe: 15.2, debt: "Zero", growth5Y: "14.9%" },
    { name: "MRF", category: "automobiles", detail: "Tyres", bucket: "compounders", tier: "Strong", pe: 28.9, roe: 13.8, debt: "Low", growth5Y: "11.2%" },
    { name: "Apollo Tyres", category: "automobiles", detail: "Tyres", bucket: "cyclical", tier: "Good", pe: 18.4, roe: 14.5, debt: "Low", growth5Y: "12.8%" },
    { name: "CEAT", category: "automobiles", detail: "Tyres", bucket: "cyclical", tier: "Good", pe: 21.5, roe: 16.2, debt: "Low", growth5Y: "13.4%" },
    { name: "Balkrishna Industries", category: "automobiles", detail: "Off-highway tyres", bucket: "compounders", tier: "Strong", pe: 38.2, roe: 18.4, debt: "Zero", growth5Y: "15.1%" },
    { name: "Tube Investments", category: "automobiles", detail: "Engineering and mobility", bucket: "growth", tier: "Strong", pe: 85.0, roe: 24.1, debt: "Zero", growth5Y: "31.2%" },
    { name: "Sundram Fasteners", category: "automobiles", detail: "Auto components", bucket: "compounders", tier: "Strong", pe: 44.1, roe: 18.5, debt: "Low", growth5Y: "13.8%" },
    { name: "Craftsman Automation", category: "automobiles", detail: "Automotive and industrial components", bucket: "growth", tier: "Strong", pe: 45.2, roe: 17.2, debt: "Low", growth5Y: "24.5%" },
    { name: "Cummins India", category: "automobiles", detail: "Engines", bucket: "compounders", tier: "Strong", pe: 44.8, roe: 21.5, debt: "Zero", growth5Y: "16.8%" },
    { name: "Gabriel India", category: "automobiles", detail: "Suspension systems", bucket: "growth", tier: "Good", pe: 34.2, roe: 18.9, debt: "Zero", growth5Y: "15.4%" },
    { name: "Schaeffler India", category: "automobiles", detail: "Bearings and automotive components", bucket: "compounders", tier: "Strong", pe: 54.1, roe: 21.4, debt: "Zero", growth5Y: "17.2%" },
    { name: "ZF Commercial Vehicle Control Systems", category: "automobiles", detail: "Commercial-vehicle systems", bucket: "compounders", tier: "Strong", pe: 65.2, roe: 18.2, debt: "Zero", growth5Y: "16.9%" },
    { name: "Suprajit Engineering", category: "automobiles", detail: "Cables and automotive components", bucket: "compounders", tier: "Good", pe: 36.4, roe: 14.8, debt: "Low", growth5Y: "14.1%" },
    { name: "Jamna Auto Industries", category: "automobiles", detail: "Suspension systems", bucket: "cyclical", tier: "Good", pe: 24.1, roe: 25.4, debt: "Zero", growth5Y: "16.5%" },
    { name: "Lumax Industries", category: "automobiles", detail: "Automotive lighting", bucket: "growth", tier: "Good", pe: 28.5, roe: 16.2, debt: "Low", growth5Y: "14.8%" },
    { name: "Varroc Engineering", category: "automobiles", detail: "Automotive lighting/components", bucket: "turnaround", tier: "Good", pe: 22.4, roe: 18.1, debt: "Low", growth5Y: "18.2%" },
    { name: "Olectra Greentech", category: "automobiles", detail: "Electric buses", bucket: "high-risk", tier: "Risky", pe: 115.0, roe: 9.4, debt: "Low", growth5Y: "45.0%" },
    { name: "JBM Auto", category: "automobiles", detail: "Buses and EV mobility", bucket: "high-risk", tier: "Risky", pe: 125.0, roe: 12.8, debt: "Moderate", growth5Y: "38.2%" },
    { name: "Ola Electric Mobility", category: "automobiles", detail: "Electric scooters", bucket: "high-risk", tier: "Risky", pe: -18.5, roe: -24.5, debt: "Moderate", growth5Y: "85.0%" },
    { name: "Hyundai Motor India", category: "automobiles", detail: "Passenger cars", bucket: "compounders", tier: "Strong", pe: 26.4, roe: 28.5, debt: "Zero", growth5Y: "15.4%" },

    // 5. IT & Technology
    { name: "TCS", category: "it-technology", detail: "IT services and consulting", bucket: "compounders", tier: "Strong", pe: 31.4, roe: 48.2, debt: "Zero", growth5Y: "10.8%" },
    { name: "Infosys", category: "it-technology", detail: "IT services", bucket: "compounders", tier: "Strong", pe: 28.2, roe: 31.5, debt: "Zero", growth5Y: "12.4%" },
    { name: "HCLTech", category: "it-technology", detail: "IT services", bucket: "compounders", tier: "Strong", pe: 27.5, roe: 24.8, debt: "Zero", growth5Y: "11.9%" },
    { name: "Wipro", category: "it-technology", detail: "IT services", bucket: "turnaround", tier: "Average", pe: 23.4, roe: 15.8, debt: "Zero", growth5Y: "7.5%" },
    { name: "Tech Mahindra", category: "it-technology", detail: "IT and telecom services", bucket: "turnaround", tier: "Good", pe: 34.2, roe: 12.4, debt: "Zero", growth5Y: "8.1%" },
    { name: "LTIMindtree", category: "it-technology", detail: "IT services", bucket: "growth", tier: "Strong", pe: 34.8, roe: 25.4, debt: "Zero", growth5Y: "17.5%" },
    { name: "Persistent Systems", category: "it-technology", detail: "Software and IT services", bucket: "growth", tier: "Strong", pe: 58.4, roe: 23.8, debt: "Zero", growth5Y: "24.8%" },
    { name: "Mphasis", category: "it-technology", detail: "IT services", bucket: "compounders", tier: "Good", pe: 31.2, roe: 20.4, debt: "Zero", growth5Y: "12.8%" },
    { name: "Coforge", category: "it-technology", detail: "IT services", bucket: "growth", tier: "Strong", pe: 42.1, roe: 24.1, debt: "Low", growth5Y: "21.4%" },
    { name: "Hexaware Technologies", category: "it-technology", detail: "IT services", bucket: "growth", tier: "Good", pe: 28.5, roe: 22.1, debt: "Zero", growth5Y: "14.5%" },
    { name: "Oracle Financial Services Software", category: "it-technology", detail: "Banking software", bucket: "compounders", tier: "Strong", pe: 38.5, roe: 32.4, debt: "Zero", growth5Y: "11.2%" },
    { name: "KPIT Technologies", category: "it-technology", detail: "Automotive software", bucket: "growth", tier: "Strong", pe: 64.2, roe: 28.9, debt: "Zero", growth5Y: "32.4%" },
    { name: "Tata Elxsi", category: "it-technology", detail: "Automotive/media technology", bucket: "growth", tier: "Strong", pe: 54.1, roe: 34.2, debt: "Zero", growth5Y: "21.5%" },
    { name: "Cyient", category: "it-technology", detail: "Engineering and technology", bucket: "turnaround", tier: "Good", pe: 28.4, roe: 17.5, debt: "Low", growth5Y: "12.4%" },
    { name: "Birlasoft", category: "it-technology", detail: "IT services", bucket: "turnaround", tier: "Good", pe: 29.5, roe: 19.8, debt: "Zero", growth5Y: "14.1%" },
    { name: "Tata Technologies", category: "it-technology", detail: "Engineering and product development", bucket: "growth", tier: "Strong", pe: 62.1, roe: 24.5, debt: "Zero", growth5Y: "18.9%" },
    { name: "eClerx Services", category: "it-technology", detail: "Business/IT services", bucket: "compounders", tier: "Strong", pe: 24.2, roe: 22.8, debt: "Zero", growth5Y: "15.4%" },
    { name: "Sonata Software", category: "it-technology", detail: "IT services", bucket: "growth", tier: "Good", pe: 38.4, roe: 31.2, debt: "Zero", growth5Y: "22.1%" },
    { name: "Zensar Technologies", category: "it-technology", detail: "IT services", bucket: "turnaround", tier: "Good", pe: 26.5, roe: 18.4, debt: "Zero", growth5Y: "10.8%" },
    { name: "Happiest Minds", category: "it-technology", detail: "Digital IT services", bucket: "growth", tier: "Good", pe: 52.1, roe: 19.8, debt: "Low", growth5Y: "21.0%" },
    { name: "Newgen Software", category: "it-technology", detail: "Enterprise software", bucket: "growth", tier: "Strong", pe: 48.5, roe: 22.5, debt: "Zero", growth5Y: "23.4%" },
    { name: "Tanla Platforms", category: "it-technology", detail: "Cloud communications", bucket: "turnaround", tier: "Average", pe: 22.1, roe: 31.4, debt: "Zero", growth5Y: "25.1%" },
    { name: "Affle India", category: "it-technology", detail: "Mobile advertising technology", bucket: "growth", tier: "Strong", pe: 58.4, roe: 19.4, debt: "Zero", growth5Y: "34.8%" },
    { name: "Route Mobile", category: "it-technology", detail: "Cloud communications", bucket: "growth", tier: "Good", pe: 32.4, roe: 16.8, debt: "Low", growth5Y: "28.5%" },
    { name: "Intellect Design Arena", category: "it-technology", detail: "Financial software", bucket: "growth", tier: "Good", pe: 35.2, roe: 18.2, debt: "Zero", growth5Y: "17.4%" },
    { name: "Mastek", category: "it-technology", detail: "Digital technology", bucket: "growth", tier: "Good", pe: 29.4, roe: 17.9, debt: "Low", growth5Y: "19.2%" },
    { name: "Firstsource Solutions", category: "it-technology", detail: "Business-process services", bucket: "compounders", tier: "Good", pe: 28.1, roe: 15.4, debt: "Low", growth5Y: "13.2%" },

    // 6. FMCG & Everyday Consumer Products
    { name: "Hindustan Unilever", category: "fmcg", detail: "Food, personal care and household products", bucket: "compounders", tier: "Strong", pe: 58.2, roe: 28.5, debt: "Zero", growth5Y: "9.5%" },
    { name: "ITC", category: "fmcg", detail: "FMCG, cigarettes, hotels and paper", bucket: "compounders", tier: "Strong", pe: 28.4, roe: 29.1, debt: "Zero", growth5Y: "11.8%" },
    { name: "Nestlé India", category: "fmcg", detail: "Food and beverages", bucket: "compounders", tier: "Strong", pe: 75.4, roe: 108.0, debt: "Zero", growth5Y: "11.2%" },
    { name: "Britannia Industries", category: "fmcg", detail: "Biscuits and dairy products", bucket: "compounders", tier: "Strong", pe: 56.4, roe: 52.1, debt: "Low", growth5Y: "10.4%" },
    { name: "Tata Consumer Products", category: "fmcg", detail: "Tea, coffee, salt and food", bucket: "compounders", tier: "Strong", pe: 82.1, roe: 8.5, debt: "Zero", growth5Y: "14.8%" },
    { name: "Dabur India", category: "fmcg", detail: "Ayurvedic and consumer products", bucket: "compounders", tier: "Good", pe: 52.4, roe: 19.8, debt: "Zero", growth5Y: "8.9%" },
    { name: "Marico", category: "fmcg", detail: "Edible oils and personal care", bucket: "compounders", tier: "Strong", pe: 54.1, roe: 36.2, debt: "Zero", growth5Y: "8.4%" },
    { name: "Godrej Consumer Products", category: "fmcg", detail: "Household and personal care", bucket: "compounders", tier: "Strong", pe: 64.2, roe: 18.5, debt: "Zero", growth5Y: "9.8%" },
    { name: "Colgate-Palmolive India", category: "fmcg", detail: "Oral-care products", bucket: "compounders", tier: "Strong", pe: 58.9, roe: 74.5, debt: "Zero", growth5Y: "8.2%" },
    { name: "Procter & Gamble Hygiene", category: "fmcg", detail: "Personal care", bucket: "compounders", tier: "Strong", pe: 72.1, roe: 78.4, debt: "Zero", growth5Y: "9.1%" },
    { name: "United Spirits", category: "fmcg", detail: "Branded beverages", bucket: "compounders", tier: "Strong", pe: 62.4, roe: 21.4, debt: "Zero", growth5Y: "12.5%" },
    { name: "Varun Beverages", category: "fmcg", detail: "PepsiCo beverages", bucket: "growth", tier: "Strong", pe: 85.0, roe: 27.8, debt: "Low", growth5Y: "28.9%" },
    { name: "United Breweries", category: "fmcg", detail: "Beer", bucket: "compounders", tier: "Good", pe: 88.2, roe: 10.5, debt: "Zero", growth5Y: "7.8%" },
    { name: "Emami", category: "fmcg", detail: "Personal care and healthcare products", bucket: "compounders", tier: "Good", pe: 35.4, roe: 26.8, debt: "Zero", growth5Y: "7.4%" },
    { name: "Jyothy Labs", category: "fmcg", detail: "Household products", bucket: "growth", tier: "Strong", pe: 42.1, roe: 18.9, debt: "Zero", growth5Y: "13.5%" },
    { name: "Zydus Wellness", category: "fmcg", detail: "Consumer healthcare", bucket: "turnaround", tier: "Good", pe: 48.5, roe: 5.4, debt: "Zero", growth5Y: "6.8%" },
    { name: "Honasa Consumer", category: "fmcg", detail: "Beauty and personal care", bucket: "high-risk", tier: "Risky", pe: 95.0, roe: 12.1, debt: "Zero", growth5Y: "45.0%" },
    { name: "Patanjali Foods", category: "fmcg", detail: "Edible oils and FMCG", bucket: "turnaround", tier: "Good", pe: 48.2, roe: 13.8, debt: "Low", growth5Y: "19.5%" },
    { name: "Bikaji Foods", category: "fmcg", detail: "Indian snacks", bucket: "growth", tier: "Strong", pe: 68.4, roe: 18.2, debt: "Zero", growth5Y: "22.4%" },
    { name: "Mrs Bectors Food", category: "fmcg", detail: "Biscuits and bakery", bucket: "growth", tier: "Strong", pe: 62.1, roe: 20.4, debt: "Zero", growth5Y: "21.5%" },
    { name: "Dodla Dairy", category: "fmcg", detail: "Dairy products", bucket: "growth", tier: "Good", pe: 34.2, roe: 16.5, debt: "Zero", growth5Y: "15.8%" },
    { name: "Heritage Foods", category: "fmcg", detail: "Dairy", bucket: "growth", tier: "Good", pe: 38.5, roe: 14.2, debt: "Low", growth5Y: "12.4%" },
    { name: "Hatsun Agro", category: "fmcg", detail: "Dairy", bucket: "compounders", tier: "Good", pe: 74.2, roe: 16.8, debt: "Moderate", growth5Y: "14.1%" },
    { name: "Avanti Feeds", category: "fmcg", detail: "Aquaculture feed", bucket: "cyclical", tier: "Good", pe: 24.1, roe: 18.5, debt: "Zero", growth5Y: "10.2%" },
    { name: "Godrej Agrovet", category: "fmcg", detail: "Agricultural and food products", bucket: "cyclical", tier: "Good", pe: 38.4, roe: 12.4, debt: "Low", growth5Y: "11.5%" },
    { name: "KRBL", category: "fmcg", detail: "Basmati rice", bucket: "compounders", tier: "Good", pe: 14.5, roe: 13.8, debt: "Zero", growth5Y: "9.2%" },
    { name: "LT Foods", category: "fmcg", detail: "Rice and packaged foods", bucket: "growth", tier: "Strong", pe: 15.2, roe: 17.5, debt: "Low", growth5Y: "16.4%" },

    // 7. Chemicals
    { name: "UPL", category: "chemicals", detail: "Agrochemicals", bucket: "turnaround", tier: "Risky", pe: 28.5, roe: 5.2, debt: "High", growth5Y: "8.4%" },
    { name: "SRF", category: "chemicals", detail: "Specialty chemicals and industrial materials", bucket: "compounders", tier: "Strong", pe: 42.1, roe: 17.8, debt: "Low", growth5Y: "18.9%" },
    { name: "PI Industries", category: "chemicals", detail: "Agrochemicals", bucket: "compounders", tier: "Strong", pe: 38.5, roe: 21.4, debt: "Zero", growth5Y: "21.5%" },
    { name: "Deepak Nitrite", category: "chemicals", detail: "Specialty chemicals", bucket: "compounders", tier: "Strong", pe: 44.2, roe: 22.1, debt: "Zero", growth5Y: "24.8%" },
    { name: "Aarti Industries", category: "chemicals", detail: "Specialty chemicals", bucket: "cyclical", tier: "Average", pe: 38.4, roe: 10.5, debt: "Moderate", growth5Y: "12.1%" },
    { name: "Navin Fluorine", category: "chemicals", detail: "Fluorochemicals", bucket: "growth", tier: "Good", pe: 65.2, roe: 11.4, debt: "Low", growth5Y: "19.5%" },
    { name: "Gujarat Fluorochemicals", category: "chemicals", detail: "Fluorochemicals", bucket: "growth", tier: "Good", pe: 58.4, roe: 14.8, debt: "Low", growth5Y: "21.0%" },
    { name: "Atul", category: "chemicals", detail: "Specialty chemicals", bucket: "compounders", tier: "Good", pe: 45.2, roe: 12.4, debt: "Zero", growth5Y: "10.8%" },
    { name: "Vinati Organics", category: "chemicals", detail: "Specialty chemicals", bucket: "compounders", tier: "Strong", pe: 52.1, roe: 20.4, debt: "Zero", growth5Y: "15.4%" },
    { name: "Clean Science", category: "chemicals", detail: "Specialty chemicals", bucket: "compounders", tier: "Strong", pe: 54.2, roe: 28.5, debt: "Zero", growth5Y: "22.1%" },
    { name: "Fine Organic Industries", category: "chemicals", detail: "Food additives and specialty chemicals", bucket: "compounders", tier: "Strong", pe: 42.8, roe: 25.1, debt: "Zero", growth5Y: "19.8%" },
    { name: "Tata Chemicals", category: "chemicals", detail: "Soda ash and specialty chemicals", bucket: "cyclical", tier: "Average", pe: 32.1, roe: 6.8, debt: "Moderate", growth5Y: "9.4%" },
    { name: "Gujarat Alkalies", category: "chemicals", detail: "Industrial chemicals", bucket: "cyclical", tier: "Average", pe: 24.5, roe: 4.5, debt: "Low", growth5Y: "8.1%" },
    { name: "Alkyl Amines", category: "chemicals", detail: "Specialty chemicals", bucket: "cyclical", tier: "Good", pe: 48.5, roe: 16.2, debt: "Zero", growth5Y: "14.2%" },
    { name: "Balaji Amines", category: "chemicals", detail: "Specialty chemicals", bucket: "cyclical", tier: "Good", pe: 38.2, roe: 18.9, debt: "Zero", growth5Y: "16.8%" },
    { name: "Anupam Rasayan", category: "chemicals", detail: "Specialty chemicals", bucket: "growth", tier: "Good", pe: 62.4, roe: 9.8, debt: "Moderate", growth5Y: "24.1%" },
    { name: "Galaxy Surfactants", category: "chemicals", detail: "Specialty chemicals", bucket: "compounders", tier: "Good", pe: 32.1, roe: 16.4, debt: "Zero", growth5Y: "11.5%" },
    { name: "NOCIL", category: "chemicals", detail: "Rubber chemicals", bucket: "cyclical", tier: "Good", pe: 34.5, roe: 9.5, debt: "Zero", growth5Y: "8.9%" },
    { name: "PCBL Chemical", category: "chemicals", detail: "Carbon black", bucket: "growth", tier: "Strong", pe: 22.4, roe: 17.8, debt: "Low", growth5Y: "18.2%" },
    { name: "Coromandel International", category: "chemicals", detail: "Fertilisers and agrochemicals", bucket: "compounders", tier: "Strong", pe: 24.5, roe: 22.4, debt: "Zero", growth5Y: "14.8%" },
    { name: "Chambal Fertilisers", category: "chemicals", detail: "Fertilisers", bucket: "cyclical", tier: "Good", pe: 11.8, roe: 21.5, debt: "Low", growth5Y: "12.4%" },
    { name: "Rallis India", category: "chemicals", detail: "Agricultural chemicals", bucket: "turnaround", tier: "Average", pe: 34.2, roe: 8.9, debt: "Zero", growth5Y: "7.1%" },
    { name: "Sumitomo Chemical India", category: "chemicals", detail: "Agrochemicals", bucket: "compounders", tier: "Strong", pe: 52.4, roe: 20.1, debt: "Zero", growth5Y: "15.9%" },
    { name: "BASF India", category: "chemicals", detail: "Chemicals", bucket: "turnaround", tier: "Strong", pe: 38.5, roe: 18.9, debt: "Zero", growth5Y: "17.2%" },
    { name: "Bayer Cropscience", category: "chemicals", detail: "Agricultural chemicals", bucket: "compounders", tier: "Good", pe: 34.8, roe: 21.2, debt: "Zero", growth5Y: "9.8%" },

    // 8. Metals & Mining
    { name: "Tata Steel", category: "metals-mining", detail: "Steel", bucket: "cyclical", tier: "Good", pe: 42.0, roe: 6.8, debt: "Moderate", growth5Y: "14.2%" },
    { name: "JSW Steel", category: "metals-mining", detail: "Steel", bucket: "cyclical", tier: "Strong", pe: 28.4, roe: 14.2, debt: "Moderate", growth5Y: "16.8%" },
    { name: "Hindalco Industries", category: "metals-mining", detail: "Aluminium and copper", bucket: "cyclical", tier: "Strong", pe: 14.8, roe: 13.5, debt: "Moderate", growth5Y: "15.4%" },
    { name: "Vedanta", category: "metals-mining", detail: "Metals and mining", bucket: "cyclical", tier: "Risky", pe: 12.5, roe: 28.4, debt: "High", growth5Y: "11.2%" },
    { name: "Jindal Steel & Power", category: "metals-mining", detail: "Steel", bucket: "cyclical", tier: "Strong", pe: 18.2, roe: 16.9, debt: "Low", growth5Y: "18.5%" },
    { name: "NMDC", category: "metals-mining", detail: "Iron ore mining", bucket: "cyclical", tier: "Good", pe: 11.4, roe: 27.5, debt: "Zero", growth5Y: "12.8%" },
    { name: "Coal India", category: "metals-mining", detail: "Coal mining", bucket: "turnaround", tier: "Strong", pe: 8.2, roe: 52.1, debt: "Zero", growth5Y: "14.5%" },
    { name: "National Aluminium", category: "metals-mining", detail: "Aluminium", bucket: "cyclical", tier: "Good", pe: 14.2, roe: 15.8, debt: "Zero", growth5Y: "13.1%" },
    { name: "Hindustan Zinc", category: "metals-mining", detail: "Zinc and lead", bucket: "cyclical", tier: "Good", pe: 18.5, roe: 42.1, debt: "Moderate", growth5Y: "10.4%" },
    { name: "Steel Authority of India", category: "metals-mining", detail: "Steel", bucket: "cyclical", tier: "Average", pe: 18.4, roe: 6.2, debt: "Moderate", growth5Y: "11.5%" },
    { name: "Jindal Stainless", category: "metals-mining", detail: "Stainless steel", bucket: "cyclical", tier: "Strong", pe: 21.4, roe: 22.8, debt: "Low", growth5Y: "24.8%" },
    { name: "MOIL", category: "metals-mining", detail: "Manganese mining", bucket: "cyclical", tier: "Good", pe: 18.2, roe: 16.4, debt: "Zero", growth5Y: "11.8%" },
    { name: "Gujarat Mineral Development", category: "metals-mining", detail: "Mineral mining", bucket: "cyclical", tier: "Good", pe: 12.4, roe: 18.2, debt: "Zero", growth5Y: "15.4%" },
    { name: "Kalyani Steels", category: "metals-mining", detail: "Steel", bucket: "cyclical", tier: "Good", pe: 14.8, roe: 15.1, debt: "Zero", growth5Y: "12.1%" },
    { name: "Shyam Metalics", category: "metals-mining", detail: "Steel and ferro alloys", bucket: "cyclical", tier: "Good", pe: 19.5, roe: 14.8, debt: "Zero", growth5Y: "21.0%" },

    // 9. Oil, Gas & Energy
    { name: "Reliance Industries", category: "oil-gas-energy", detail: "Oil refining, petrochemicals, retail and telecom", bucket: "compounders", tier: "Strong", pe: 26.4, roe: 9.8, debt: "Low", growth5Y: "15.8%" },
    { name: "ONGC", category: "oil-gas-energy", detail: "Oil and gas exploration", bucket: "turnaround", tier: "Strong", pe: 7.4, roe: 15.2, debt: "Low", growth5Y: "16.2%" },
    { name: "Indian Oil", category: "oil-gas-energy", detail: "Refining and fuel distribution", bucket: "turnaround", tier: "Good", pe: 11.2, roe: 16.5, debt: "Moderate", growth5Y: "14.1%" },
    { name: "BPCL", category: "oil-gas-energy", detail: "Refining and fuel distribution", bucket: "turnaround", tier: "Good", pe: 9.8, roe: 24.1, debt: "Moderate", growth5Y: "15.8%" },
    { name: "HPCL", category: "oil-gas-energy", detail: "Refining and fuel distribution", bucket: "turnaround", tier: "Good", pe: 8.5, roe: 22.8, debt: "High", growth5Y: "14.9%" },
    { name: "GAIL", category: "oil-gas-energy", detail: "Natural-gas transmission", bucket: "turnaround", tier: "Strong", pe: 12.8, roe: 15.4, debt: "Low", growth5Y: "17.2%" },
    { name: "Oil India", category: "oil-gas-energy", detail: "Oil and gas exploration", bucket: "turnaround", tier: "Strong", pe: 8.9, roe: 18.2, debt: "Low", growth5Y: "18.5%" },
    { name: "Petronet LNG", category: "oil-gas-energy", detail: "LNG import and regasification", bucket: "compounders", tier: "Strong", pe: 13.5, roe: 23.4, debt: "Zero", growth5Y: "10.2%" },
    { name: "Gujarat Gas", category: "oil-gas-energy", detail: "City-gas distribution", bucket: "growth", tier: "Good", pe: 32.4, roe: 18.5, debt: "Zero", growth5Y: "14.8%" },
    { name: "Indraprastha Gas", category: "oil-gas-energy", detail: "City-gas distribution", bucket: "compounders", tier: "Strong", pe: 19.5, roe: 20.1, debt: "Zero", growth5Y: "16.1%" },
    { name: "Mahanagar Gas", category: "oil-gas-energy", detail: "City-gas distribution", bucket: "compounders", tier: "Strong", pe: 14.8, roe: 24.8, debt: "Zero", growth5Y: "15.4%" },
    { name: "Adani Total Gas", category: "oil-gas-energy", detail: "City-gas distribution", bucket: "high-risk", tier: "Risky", pe: 145.0, roe: 18.2, debt: "Moderate", growth5Y: "24.5%" },
    { name: "Aegis Logistics", category: "oil-gas-energy", detail: "LPG and logistics", bucket: "growth", tier: "Strong", pe: 42.1, roe: 18.9, debt: "Low", growth5Y: "21.0%" },
    { name: "Gujarat State Petronet", category: "oil-gas-energy", detail: "Gas pipelines", bucket: "compounders", tier: "Strong", pe: 11.2, roe: 16.4, debt: "Low", growth5Y: "12.8%" },
    { name: "Chennai Petroleum", category: "oil-gas-energy", detail: "Oil refining", bucket: "cyclical", tier: "Good", pe: 6.8, roe: 32.4, debt: "Low", growth5Y: "25.1%" },
    { name: "Castrol India", category: "oil-gas-energy", detail: "Lubricants", bucket: "compounders", tier: "Good", pe: 24.5, roe: 48.5, debt: "Zero", growth5Y: "6.8%" },
    { name: "Nayara Energy", category: "oil-gas-energy", detail: "Refining and fuel", bucket: "turnaround", tier: "Average", pe: 8.0, roe: 14.0, debt: "Moderate", growth5Y: "10.0%" },
    { name: "NTPC", category: "oil-gas-energy", detail: "Electricity generation", bucket: "turnaround", tier: "Strong", pe: 18.5, roe: 13.8, debt: "High", growth5Y: "14.2%" },
    { name: "Power Grid", category: "oil-gas-energy", detail: "Electricity transmission", bucket: "compounders", tier: "Strong", pe: 19.2, roe: 18.9, debt: "High", growth5Y: "10.5%" },
    { name: "Tata Power", category: "oil-gas-energy", detail: "Electricity generation and distribution", bucket: "growth", tier: "Strong", pe: 38.4, roe: 12.5, debt: "High", growth5Y: "18.9%" },
    { name: "Adani Power", category: "oil-gas-energy", detail: "Electricity generation", bucket: "turnaround", tier: "Good", pe: 14.8, roe: 38.2, debt: "Moderate", growth5Y: "28.5%" },
    { name: "JSW Energy", category: "oil-gas-energy", detail: "Electricity generation", bucket: "growth", tier: "Strong", pe: 58.2, roe: 10.4, debt: "Moderate", growth5Y: "21.4%" },
    { name: "NHPC", category: "oil-gas-energy", detail: "Hydroelectric power", bucket: "compounders", tier: "Good", pe: 24.1, roe: 10.8, debt: "High", growth5Y: "8.9%" },
    { name: "SJVN", category: "oil-gas-energy", detail: "Hydroelectric and renewable power", bucket: "growth", tier: "Good", pe: 42.5, roe: 9.5, debt: "High", growth5Y: "14.2%" },
    { name: "Torrent Power", category: "oil-gas-energy", detail: "Electricity generation/distribution", bucket: "compounders", tier: "Strong", pe: 32.4, roe: 17.5, debt: "Moderate", growth5Y: "15.1%" },
    { name: "CESC", category: "oil-gas-energy", detail: "Electricity", bucket: "compounders", tier: "Good", pe: 15.4, roe: 13.2, debt: "High", growth5Y: "7.8%" },
    { name: "NLC India", category: "oil-gas-energy", detail: "Mining and power", bucket: "turnaround", tier: "Good", pe: 18.2, roe: 12.1, debt: "Moderate", growth5Y: "11.4%" },
    { name: "Waaree Energies", category: "oil-gas-energy", detail: "Solar modules", bucket: "growth", tier: "Strong", pe: 45.0, roe: 34.5, debt: "Low", growth5Y: "48.5%" },
    { name: "KPI Green Energy", category: "oil-gas-energy", detail: "Solar power", bucket: "growth", tier: "Strong", pe: 48.2, roe: 28.9, debt: "Moderate", growth5Y: "52.1%" },
    { name: "ACME Solar", category: "oil-gas-energy", detail: "Solar power", bucket: "growth", tier: "Good", pe: 38.0, roe: 18.5, debt: "Moderate", growth5Y: "32.0%" },

    // 10. Consumer Durables & Electronics
    { name: "Whirlpool India", category: "consumer-durables", detail: "Home appliances", bucket: "turnaround", tier: "Average", pe: 52.4, roe: 7.8, debt: "Zero", growth5Y: "6.2%" },
    { name: "Crompton Greaves Consumer", category: "consumer-durables", detail: "Fans and appliances", bucket: "compounders", tier: "Good", pe: 44.2, roe: 16.5, debt: "Zero", growth5Y: "10.4%" },
    { name: "Orient Electric", category: "consumer-durables", detail: "Fans and lighting", bucket: "turnaround", tier: "Average", pe: 42.1, roe: 14.2, debt: "Zero", growth5Y: "8.5%" },
    { name: "Amber Enterprises", category: "consumer-durables", detail: "Air-conditioner components", bucket: "growth", tier: "Strong", pe: 72.4, roe: 11.5, debt: "Low", growth5Y: "24.1%" },
    { name: "PG Electroplast", category: "consumer-durables", detail: "Appliances and electronics", bucket: "growth", tier: "Strong", pe: 64.2, roe: 22.8, debt: "Low", growth5Y: "38.5%" },
    { name: "Symphony", category: "consumer-durables", detail: "Air coolers", bucket: "compounders", tier: "Good", pe: 48.5, roe: 21.4, debt: "Zero", growth5Y: "9.2%" },
    { name: "Titan Company", category: "consumer-durables", detail: "Jewellery and watches", bucket: "compounders", tier: "Strong", pe: 82.4, roe: 31.2, debt: "Zero", growth5Y: "21.5%" },
    { name: "Kalyan Jewellers", category: "consumer-durables", detail: "Jewellery", bucket: "growth", tier: "Strong", pe: 68.2, roe: 18.4, debt: "Moderate", growth5Y: "28.4%" },
    { name: "Trent", category: "consumer-durables", detail: "Retail", bucket: "growth", tier: "Strong", pe: 145.0, roe: 38.5, debt: "Low", growth5Y: "36.2%" },
    { name: "Bata India", category: "consumer-durables", detail: "Footwear", bucket: "turnaround", tier: "Average", pe: 54.2, roe: 12.8, debt: "Zero", growth5Y: "5.4%" },

    // 11. Construction & Infrastructure
    { name: "IRB Infrastructure", category: "construction-infra", detail: "Highways", bucket: "growth", tier: "Good", pe: 45.2, roe: 8.5, debt: "High", growth5Y: "18.4%" },
    { name: "G R Infraprojects", category: "construction-infra", detail: "Roads", bucket: "compounders", tier: "Strong", pe: 16.4, roe: 18.2, debt: "Low", growth5Y: "17.5%" },
    { name: "Dilip Buildcon", category: "construction-infra", detail: "Infrastructure", bucket: "turnaround", tier: "Average", pe: 22.4, roe: 9.2, debt: "Moderate", growth5Y: "11.2%" },
    { name: "J Kumar Infraprojects", category: "construction-infra", detail: "Urban infrastructure", bucket: "growth", tier: "Strong", pe: 15.8, roe: 15.4, debt: "Low", growth5Y: "19.2%" },
    { name: "Afcons Infrastructure", category: "construction-infra", detail: "Infrastructure construction", bucket: "growth", tier: "Strong", pe: 28.0, roe: 16.5, debt: "Moderate", growth5Y: "16.8%" },
    { name: "RailTel", category: "construction-infra", detail: "Railway telecom infrastructure", bucket: "growth", tier: "Strong", pe: 42.1, roe: 18.9, debt: "Zero", growth5Y: "21.4%" },

    // 12. Cement & Building Materials
    { name: "UltraTech Cement", category: "cement-materials", detail: "Cement", bucket: "compounders", tier: "Strong", pe: 45.2, roe: 14.8, debt: "Low", growth5Y: "13.5%" },
    { name: "Shree Cement", category: "cement-materials", detail: "Cement", bucket: "compounders", tier: "Strong", pe: 42.8, roe: 13.2, debt: "Zero", growth5Y: "11.8%" },
    { name: "Dalmia Bharat", category: "cement-materials", detail: "Cement", bucket: "growth", tier: "Good", pe: 38.4, roe: 8.9, debt: "Low", growth5Y: "14.2%" },
    { name: "Ambuja Cements", category: "cement-materials", detail: "Cement", bucket: "compounders", tier: "Strong", pe: 41.2, roe: 12.5, debt: "Zero", growth5Y: "12.1%" },
    { name: "ACC", category: "cement-materials", detail: "Cement", bucket: "compounders", tier: "Good", pe: 24.5, roe: 14.1, debt: "Zero", growth5Y: "10.4%" },
    { name: "JK Cement", category: "cement-materials", detail: "Cement", bucket: "compounders", tier: "Strong", pe: 35.2, roe: 16.8, debt: "Moderate", growth5Y: "16.2%" },
    { name: "Ramco Cements", category: "cement-materials", detail: "Cement", bucket: "cyclical", tier: "Good", pe: 48.5, roe: 7.8, debt: "Moderate", growth5Y: "11.5%" },
    { name: "Birla Corporation", category: "cement-materials", detail: "Cement", bucket: "cyclical", tier: "Good", pe: 28.4, roe: 9.5, debt: "Moderate", growth5Y: "12.8%" },
    { name: "India Cements", category: "cement-materials", detail: "Cement", bucket: "turnaround", tier: "Risky", pe: -35.0, roe: -4.2, debt: "High", growth5Y: "3.5%" },
    { name: "Kajaria Ceramics", category: "cement-materials", detail: "Tiles", bucket: "compounders", tier: "Strong", pe: 48.2, roe: 18.5, debt: "Zero", growth5Y: "11.9%" },
    { name: "Supreme Industries", category: "cement-materials", detail: "Plastic pipes/building products", bucket: "compounders", tier: "Strong", pe: 54.1, roe: 24.8, debt: "Zero", growth5Y: "17.4%" },

    // 13. Realty
    { name: "DLF", category: "realty", detail: "Residential and commercial property", bucket: "growth", tier: "Strong", pe: 58.4, roe: 9.5, debt: "Zero", growth5Y: "19.5%" },
    { name: "Godrej Properties", category: "realty", detail: "Real-estate development", bucket: "growth", tier: "Strong", pe: 72.1, roe: 8.9, debt: "Low", growth5Y: "24.1%" },
    { name: "Prestige Estates", category: "realty", detail: "Real-estate development", bucket: "growth", tier: "Strong", pe: 64.2, roe: 11.2, debt: "Moderate", growth5Y: "22.8%" },
    { name: "Oberoi Realty", category: "realty", detail: "Premium real estate", bucket: "compounders", tier: "Strong", pe: 32.4, roe: 16.8, debt: "Zero", growth5Y: "18.4%" },
    { name: "Phoenix Mills", category: "realty", detail: "Shopping malls and property", bucket: "compounders", tier: "Strong", pe: 48.5, roe: 14.5, debt: "Low", growth5Y: "21.0%" },
    { name: "Brigade Enterprises", category: "realty", detail: "Real estate", bucket: "growth", tier: "Strong", pe: 42.1, roe: 13.8, debt: "Low", growth5Y: "19.8%" },
    { name: "Sobha", category: "realty", detail: "Residential real estate", bucket: "growth", tier: "Strong", pe: 68.4, roe: 8.2, debt: "Moderate", growth5Y: "17.5%" },
    { name: "Macrotech Developers", category: "realty", detail: "Real estate", bucket: "growth", tier: "Strong", pe: 52.1, roe: 14.2, debt: "Low", growth5Y: "26.4%" },
    { name: "Anant Raj", category: "realty", detail: "Real estate", bucket: "growth", tier: "Strong", pe: 58.2, roe: 12.4, debt: "Low", growth5Y: "32.1%" },
    { name: "Swan Energy", category: "realty", detail: "Real estate and energy", bucket: "high-risk", tier: "Risky", pe: 65.0, roe: 15.2, debt: "Moderate", growth5Y: "45.0%" },

    // 14. Telecom & Digital Communication
    { name: "Bharti Airtel", category: "telecom", detail: "Mobile, broadband and digital services", bucket: "growth", tier: "Strong", pe: 48.5, roe: 18.2, debt: "Moderate", growth5Y: "16.8%" },
    { name: "Vodafone Idea", category: "telecom", detail: "Mobile telecom", bucket: "high-risk", tier: "Risky", pe: -4.2, roe: -85.0, debt: "High", growth5Y: "2.1%" },
    { name: "Tata Communications", category: "telecom", detail: "Global telecom and digital infrastructure", bucket: "turnaround", tier: "Good", pe: 42.1, roe: 28.4, debt: "Moderate", growth5Y: "11.5%" },
    { name: "Indus Towers", category: "telecom", detail: "Telecom towers", bucket: "turnaround", tier: "Good", pe: 15.4, roe: 24.5, debt: "Low", growth5Y: "8.9%" },
    { name: "Tejas Networks", category: "telecom", detail: "Telecom equipment", bucket: "growth", tier: "Strong", pe: 65.0, roe: 8.5, debt: "Low", growth5Y: "35.2%" },
    { name: "HFCL", category: "telecom", detail: "Telecom equipment and fibre", bucket: "growth", tier: "Good", pe: 38.2, roe: 11.4, debt: "Low", growth5Y: "16.4%" },
    { name: "Sterlite Technologies", category: "telecom", detail: "Optical fibre and digital infrastructure", bucket: "turnaround", tier: "Average", pe: 32.1, roe: 7.2, debt: "Moderate", growth5Y: "9.8%" },

    // 15. Consumer Services, Retail, Travel & Transport
    { name: "Avenue Supermarts (DMart)", category: "consumer-services", detail: "Supermarket retail", bucket: "compounders", tier: "Strong", pe: 112.0, roe: 16.4, debt: "Zero", growth5Y: "22.5%" },
    { name: "Zomato/Eternal", category: "consumer-services", detail: "Food delivery and quick commerce", bucket: "growth", tier: "Strong", pe: 125.0, roe: 8.2, debt: "Zero", growth5Y: "48.9%" },
    { name: "Info Edge", category: "consumer-services", detail: "Internet platforms and recruitment", bucket: "compounders", tier: "Strong", pe: 74.2, roe: 14.8, debt: "Zero", growth5Y: "18.5%" },
    { name: "Indian Hotels", category: "consumer-services", detail: "Hotels", bucket: "growth", tier: "Strong", pe: 58.4, roe: 16.5, debt: "Zero", growth5Y: "21.4%" },
    { name: "ITC Hotels", category: "consumer-services", detail: "Hotels", bucket: "growth", tier: "Strong", pe: 45.0, roe: 15.0, debt: "Zero", growth5Y: "18.0%" },
    { name: "Lemon Tree Hotels", category: "consumer-services", detail: "Hotels", bucket: "growth", tier: "Good", pe: 48.2, roe: 14.1, debt: "Moderate", growth5Y: "24.5%" },
    { name: "Chalet Hotels", category: "consumer-services", detail: "Hotels", bucket: "growth", tier: "Good", pe: 52.1, roe: 12.8, debt: "Moderate", growth5Y: "22.1%" },
    { name: "InterGlobe Aviation", category: "consumer-services", detail: "IndiGo airline", bucket: "growth", tier: "Strong", pe: 21.4, roe: 42.5, debt: "Moderate", growth5Y: "25.4%" },
    { name: "IRCTC", category: "consumer-services", detail: "Railway ticketing, catering and tourism", bucket: "compounders", tier: "Strong", pe: 54.2, roe: 41.2, debt: "Zero", growth5Y: "24.8%" },
    { name: "Delhivery", category: "consumer-services", detail: "Logistics", bucket: "high-risk", tier: "Risky", pe: -45.0, roe: -2.4, debt: "Zero", growth5Y: "28.5%" },
    { name: "Blue Dart Express", category: "consumer-services", detail: "Courier/logistics", bucket: "compounders", tier: "Good", pe: 45.2, roe: 24.1, debt: "Zero", growth5Y: "14.2%" },
    { name: "Container Corporation", category: "consumer-services", detail: "Rail freight", bucket: "compounders", tier: "Good", pe: 38.4, roe: 11.5, debt: "Zero", growth5Y: "9.8%" },
    { name: "Adani Ports", category: "consumer-services", detail: "Ports and logistics", bucket: "growth", tier: "Strong", pe: 34.2, roe: 17.8, debt: "Moderate", growth5Y: "19.5%" },
    { name: "Shipping Corporation of India", category: "consumer-services", detail: "Shipping", bucket: "cyclical", tier: "Good", pe: 14.8, roe: 12.4, debt: "Low", growth5Y: "15.8%" },
    { name: "Gateway Distriparks", category: "consumer-services", detail: "Logistics", bucket: "growth", tier: "Good", pe: 22.4, roe: 15.2, debt: "Low", growth5Y: "14.1%" },
    { name: "Allcargo Logistics", category: "consumer-services", detail: "Logistics", bucket: "turnaround", tier: "Average", pe: 28.5, roe: 8.4, debt: "Low", growth5Y: "11.2%" },
    { name: "VRL Logistics", category: "consumer-services", detail: "Road logistics", bucket: "growth", tier: "Good", pe: 38.2, roe: 18.5, debt: "Low", growth5Y: "16.4%" },
    { name: "Transport Corporation of India", category: "consumer-services", detail: "Logistics", bucket: "compounders", tier: "Strong", pe: 22.1, roe: 19.4, debt: "Zero", growth5Y: "15.8%" },
    { name: "Easy Trip Planners", category: "consumer-services", detail: "Travel booking", bucket: "high-risk", tier: "Average", pe: 48.5, roe: 32.1, debt: "Zero", growth5Y: "28.4%" },
    { name: "Thomas Cook India", category: "consumer-services", detail: "Travel services", bucket: "turnaround", tier: "Good", pe: 32.4, roe: 16.8, debt: "Zero", growth5Y: "21.0%" },
    { name: "MakeMyTrip", category: "consumer-services", detail: "Online travel", bucket: "growth", tier: "Strong", pe: 65.0, roe: 18.5, debt: "Zero", growth5Y: "32.5%" },
    { name: "Jubilant FoodWorks", category: "consumer-services", detail: "Domino's and food retail", bucket: "growth", tier: "Good", pe: 85.0, roe: 14.2, debt: "Low", growth5Y: "14.8%" },
    { name: "Westlife Foodworld", category: "consumer-services", detail: "McDonald's India franchise", bucket: "growth", tier: "Good", pe: 110.0, roe: 12.1, debt: "Low", growth5Y: "16.2%" },
    { name: "Sapphire Foods", category: "consumer-services", detail: "KFC/Pizza Hut franchise", bucket: "growth", tier: "Good", pe: 74.2, roe: 10.5, debt: "Low", growth5Y: "24.1%" },
    { name: "Devyani International", category: "consumer-services", detail: "KFC/Pizza Hut/Kosta Coffee franchise", bucket: "growth", tier: "Good", pe: 95.0, roe: 9.8, debt: "Low", growth5Y: "28.5%" },
    { name: "Restaurant Brands Asia", category: "consumer-services", detail: "Burger King", bucket: "high-risk", tier: "Risky", pe: -28.0, roe: -14.5, debt: "Moderate", growth5Y: "18.2%" },
    { name: "PVR INOX", category: "consumer-services", detail: "Cinema", bucket: "turnaround", tier: "Average", pe: 85.0, roe: 3.2, debt: "Moderate", growth5Y: "12.4%" },
    { name: "Firstsource Solutions", category: "consumer-services", detail: "Business services", bucket: "compounders", tier: "Good", pe: 28.1, roe: 15.4, debt: "Low", growth5Y: "13.2%" },
    { name: "Quess Corp", category: "consumer-services", detail: "Staffing/business services", bucket: "turnaround", tier: "Good", pe: 32.4, roe: 14.8, debt: "Zero", growth5Y: "14.5%" },
    { name: "TeamLease Services", category: "consumer-services", detail: "Staffing", bucket: "turnaround", tier: "Good", pe: 38.2, roe: 15.2, debt: "Zero", growth5Y: "12.8%" },
    { name: "SIS", category: "consumer-services", detail: "Security services", bucket: "compounders", tier: "Good", pe: 21.4, roe: 13.8, debt: "Low", growth5Y: "13.4%" },
    { name: "Redington", category: "consumer-services", detail: "Technology distribution", bucket: "compounders", tier: "Strong", pe: 14.5, roe: 22.8, debt: "Low", growth5Y: "16.8%" },
    { name: "Eternal", category: "consumer-services", detail: "Internet/consumer platforms", bucket: "growth", tier: "Strong", pe: 125.0, roe: 8.2, debt: "Zero", growth5Y: "48.9%" },
    { name: "IndiaMART", category: "consumer-services", detail: "B2B online marketplace", bucket: "compounders", tier: "Strong", pe: 42.1, roe: 24.5, debt: "Zero", growth5Y: "21.0%" },
    { name: "CarTrade Tech", category: "consumer-services", detail: "Online auto marketplace", bucket: "growth", tier: "Good", pe: 48.5, roe: 7.8, debt: "Zero", growth5Y: "19.5%" },
    { name: "PB Fintech", category: "consumer-services", detail: "Online insurance/financial marketplace", bucket: "growth", tier: "Strong", pe: 145.0, roe: 6.5, debt: "Zero", growth5Y: "38.2%" },
    { name: "Nykaa", category: "consumer-services", detail: "Beauty and fashion e-commerce", bucket: "high-risk", tier: "Risky", pe: 185.0, roe: 4.2, debt: "Zero", growth5Y: "34.5%" },
    { name: "FSN E-Commerce", category: "consumer-services", detail: "Beauty e-commerce", bucket: "high-risk", tier: "Risky", pe: 185.0, roe: 4.2, debt: "Zero", growth5Y: "34.5%" },
    { name: "Affle India", category: "consumer-services", detail: "Digital advertising", bucket: "growth", tier: "Strong", pe: 58.4, roe: 19.4, debt: "Zero", growth5Y: "34.8%" },
    { name: "Yatra Online", category: "consumer-services", detail: "Travel booking", bucket: "turnaround", tier: "Average", pe: 42.0, roe: 5.8, debt: "Zero", growth5Y: "14.2%" },

    // 16. Textiles & Apparel
    { name: "Page Industries", category: "textiles-apparel", detail: "Innerwear/apparel", bucket: "compounders", tier: "Strong", pe: 62.4, roe: 45.2, debt: "Zero", growth5Y: "14.5%" },
    { name: "KPR Mill", category: "textiles-apparel", detail: "Yarn, textiles and garments", bucket: "compounders", tier: "Strong", pe: 38.5, roe: 24.1, debt: "Low", growth5Y: "18.2%" },
    { name: "Welspun Living", category: "textiles-apparel", detail: "Home textiles", bucket: "turnaround", tier: "Good", pe: 24.1, roe: 14.8, debt: "Moderate", growth5Y: "11.4%" },
    { name: "Vardhman Textiles", category: "textiles-apparel", detail: "Yarn and textiles", bucket: "cyclical", tier: "Good", pe: 18.2, roe: 9.8, debt: "Low", growth5Y: "9.5%" },
    { name: "Gokaldas Exports", category: "textiles-apparel", detail: "Garment manufacturing", bucket: "growth", tier: "Strong", pe: 28.5, roe: 18.9, debt: "Low", growth5Y: "24.8%" },

    // 17. Media & Entertainment
    { name: "Sun TV Network", category: "media-entertainment", detail: "Television broadcasting", bucket: "compounders", tier: "Strong", pe: 15.4, roe: 18.5, debt: "Zero", growth5Y: "7.8%" },
    { name: "Zee Entertainment", category: "media-entertainment", detail: "TV and entertainment", bucket: "turnaround", tier: "Risky", pe: 28.5, roe: 4.2, debt: "Zero", growth5Y: "2.1%" },
    { name: "Network18", category: "media-entertainment", detail: "News and media", bucket: "turnaround", tier: "Average", pe: 45.0, roe: 3.5, debt: "Moderate", growth5Y: "8.9%" },
    { name: "Saregama India", category: "media-entertainment", detail: "Music and entertainment", bucket: "growth", tier: "Strong", pe: 48.2, roe: 17.4, debt: "Zero", growth5Y: "21.4%" },
    { name: "PVR INOX", category: "media-entertainment", detail: "Cinema exhibition", bucket: "turnaround", tier: "Average", pe: 85.0, roe: 3.2, debt: "Moderate", growth5Y: "12.4%" }
  ]
};
